// web-next/src/views/Detail.vue
<script setup lang="ts">
/// One item's page: a film, a series, or an episode.
///
/// Three failures live here and they are three different things — see
/// `composables/item.ts`. The one that takes the screen is the item itself;
/// the children's failure is a line where the list would be; and anything you
/// asked for that did not work is a line on a page that is otherwise intact.
///
/// An album's page needs the queue that outlives it, so it lands with the
/// queue in phase 12.
import { computed, ref, watch } from 'vue'
import { useQuery } from '@tanstack/vue-query'
import { useRoute, useRouter } from 'vue-router'

import Attribution from '../components/Attribution.vue'
import Btn from '../components/Btn.vue'
import CapabilityDebug from '../components/CapabilityDebug.vue'
import SubtitlePanel from '../components/SubtitlePanel.vue'
import DetailHead from '../components/DetailHead.vue'
import Failed from '../components/Failed.vue'
import Icon from '../components/Icon.vue'
import { childCount, continueAt, ordered, seasonsIn } from '../domain/detail.ts'
import {
  deliveryPlan,
  groupSources,
  planRow,
  size,
  subtitleChip,
  subtitleChipTitle,
} from '../domain/source.ts'
import {
  episodeOf,
  projecting,
  resumeMs,
  seasonLabel,
  seasonOf,
  seLabel,
  watchedPct,
} from '../domain/label.ts'
import { adminItemLog, listLibraries } from '../api/generated/kahawai.ts'
import { notify } from '../composables/notices.ts'
import { loadMask } from '../api/capabilities.ts'
import { maskSummary } from '../domain/capability-mask.ts'
import { sentence } from '../domain/refusal.ts'
import { saveAs } from '../api/download.ts'
import { seasonSegment } from '../domain/routes.ts'
import { whoAmI } from '../api/session.ts'
import { useChildren, useItem, useWatched } from '../composables/item.ts'
import { usePrefs } from '../composables/prefs.ts'
import { useQueue } from '../composables/queue.ts'

const route = useRoute()
const router = useRouter()

const id = computed(() => String(route.params.id ?? ''))
const library = computed(() => String(route.params.library ?? ''))

const query = useItem(id)
const item = computed(() => query.data.value)
const children = useChildren(item)
const { mark, busy } = useWatched()

/// HUB-31: the projection is a preference, and it is not read yet — phase 10
/// brings Settings and with it `anime_view`. Until then the projected view is
/// the default, which is what the old client defaults to.
const projected = computed(() => projecting('seasons', children.data.value ?? []))
const episodes = computed(() => ordered(children.data.value ?? [], projected.value))
const seasons = computed(() => seasonsIn(episodes.value, projected.value))
const next = computed(() => continueAt(children.data.value ?? null))

/// Hierarchical: an episode goes up to its series, everything else to the
/// library the URL came from — the one that was navigated from, which is the
/// only thing that knows, because a collection can be in more than one.
const up = computed(() => {
  const kind = item.value?.kind
  if (kind === 'episode' && item.value?.parent_id) {
    return { label: `← ${item.value.show_title ?? 'Series'}`, id: item.value.parent_id }
  }
  return { label: '← Library', id: null }
})
function goUp() {
  if (up.value.id) {
    void router.push({ name: 'detail', params: { library: library.value, id: up.value.id } })
  } else {
    void router.push({ name: 'library', params: { library: library.value } })
  }
}

/// What playback would pick: the hub orders the list that way, so the first
/// work in it is the one Play uses.
const works = computed(() => groupSources(item.value?.sources ?? []))
const best = computed(() => works.value[0]?.parts[0])

/// HUB-24, and the two preferences the panel has to know about: the media
/// type's subtitle wishlist, and this TITLE's own standing choice — which
/// outranks it, is set by picking a language while watching, and would
/// otherwise make the list above it read as a lie.
const prefs = usePrefs()
const libraries = useQuery({
  queryKey: ['libraries'],
  queryFn: () => listLibraries(),
  select: (answer) => answer.libraries,
})
const mediaType = computed(
  () => libraries.data.value?.find((l) => l.id === library.value)?.media_type ?? '',
)
const subLanguages = computed(() =>
  (prefs.known.value[`subs.${mediaType.value}`] ?? '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean),
)
const titleScope = computed(() => item.value?.parent_id ?? item.value?.id ?? '')
const titleChoice = computed(
  () =>
    prefs.query.data.value?.prefs.find((p) => p.scope === titleScope.value && p.key === 'subs')
      ?.value ?? '',
)
/// The file's own frame rate, for the drift warning on a candidate.
const fileFps = computed(() => {
  const fps = best.value?.streams?.video?.[0]?.fps
  return fps ? fps[0] / fps[1] : null
})

/// A download, a removal or a cleared override all change what this page shows.
async function subtitlesChanged() {
  await Promise.all([query.refetch(), prefs.query.refetch()])
}

/// What the stored capability mask changes, if anything.
/// The mask this page's verdict was computed against. Re-read rather than
/// captured, because the panel below can change it — and a badge that still
/// reports the mask it USED to be is worse than no badge.
const mask = ref(loadMask())
const masked = computed(() => maskSummary(mask.value))
const showCaps = ref(false)

/// Re-ASK, do not just re-badge. The negotiated half of this page is an answer
/// to the capability profile, so editing the mask invalidates it: the delivery,
/// the ASS rung and the reasons all move.
async function maskChanged() {
  mask.value = loadMask()
  await query.refetch()
}

/// OPS-10: the LAST session for this item, whoever played it.
///
/// The point is debugging a report from somebody else, after they have closed
/// the player — so it is on the item, not on the session, and it is here
/// rather than in the admin panel because this is the page you are on when
/// somebody says "this one would not play".
const me = whoAmI()

/// A record's actions are the queue's. `playAlbum` replaces what is playing and
/// `appendAlbum` does not — both are what somebody asked for, and neither is
/// the other.
const queue = useQueue()
const tracks = computed(() => children.data.value ?? [])
/// Which track of THIS record is playing, so the list can mark it. By id: the
/// queue may hold another record entirely.
const nowPlaying = computed(() => queue.playing.value?.track.id ?? null)

/// Why the two actions cannot be pressed, or '' when they can. Said out loud
/// as well as in a title: a disabled button is out of the tab order, so its
/// tooltip is unreachable by exactly the people who need the sentence.
const whyNoTracks = computed(() => {
  if (tracks.value.length) return ''
  if (children.isError.value) return 'The track list could not be read.'
  if (children.isPending.value) return 'Still reading the track list…'
  return 'This record has no tracks.'
})
async function itemLog() {
  try {
    saveAs(`item-${id.value}.log`, await adminItemLog(id.value))
  } catch (cause) {
    notify(`Could not download the session log: ${sentence(cause)}`)
  }
}

/// A re-ask that failed under a page that is still standing. Not the screen:
/// what is on it is a moment out of date, not wrong.
watch(
  () => query.isError.value && item.value !== undefined,
  (stale) => stale && notify(`Could not re-read this item: ${sentence(query.error.value)}`),
)
const resumeAt = computed(() => (item.value ? resumeMs(item.value) : 0))

const subline = computed(() => {
  const it = item.value
  if (!it) return ''
  if (it.kind === 'show') return childCount(children.data.value ?? null, 'episode', 'episodes')
  if (it.kind === 'album') {
    return [it.artist, childCount(children.data.value ?? null, 'track', 'tracks')]
      .filter(Boolean)
      .join(' · ')
  }
  return [
    it.kind === 'episode' && it.show_title ? it.show_title : '',
    it.kind === 'episode' ? seLabel(it.season, it.episode, it.episode_end) : '',
    it.metadata?.genres?.length ? it.metadata.genres.join(' · ') : '',
  ]
    .filter(Boolean)
    .join(' · ')
})

function play(fromStart = false) {
  void router.push({
    name: 'player',
    params: { library: library.value, id: id.value },
    ...(fromStart ? { query: { start: '0' } } : {}),
  })
}

function openSeason(season: number | null) {
  void router.push({
    name: 'season',
    params: { library: library.value, id: id.value, season: seasonSegment(season) },
  })
}

function openItem(child: string) {
  void router.push({ name: 'detail', params: { library: library.value, id: child } })
}

/// One press for a season somebody has already watched elsewhere — the
/// alternative is thirteen presses. WHICH episodes are in it is decided here,
/// because the season a viewer sees can be a projection of absolute numbering
/// and the hub would have to guess.
function markSeason(season: number | null, played: boolean) {
  const inSeason = episodes.value.filter((e) => seasonOf(e, projected.value) === season)
  void mark(
    item.value!.id,
    played,
    inSeason.map((e) => e.id),
  )
}
</script>

<template>
  <!-- There is no page without the item, so this one takes the screen — and it
       offers somewhere to go, because a page you can only leave by editing the
       URL is a dead end. -->
  <!-- Only when there is nothing to show. A background re-ask can fail while
       the page is perfectly good — a tick invalidates this query, so a blip
       there would have replaced a page the viewer was reading, over a write
       that had landed. -->
  <Failed
    v-if="query.isError.value && !item"
    what="Could not load this item."
    :message="sentence(query.error.value)"
    away="Back to library"
    @retry="query.refetch()"
    @away="router.push({ name: 'library', params: { library } })"
  />

  <main v-else-if="item">
    <Btn ghost small class="mb-4" @click="goUp">{{ up.label }}</Btn>

    <DetailHead :item="item" :subline="subline" :progress="item.kind === 'show' ? null : undefined">
      <template v-if="item.kind === 'show'">
        <!-- The series' one action: get on with it. Named, so it is obvious
             which episode pressing it starts — and numbered the way the list
             below is, because reading the native fields here put "Continue ·
             E10" above a row reading "S01E10". -->
        <template v-if="next">
          <Btn @click="openItem(next.id)">
            ▶ Continue ·
            {{ seLabel(seasonOf(next, projected), episodeOf(next, projected), next.episode_end) }}
          </Btn>
          <span class="text-[13px] text-dim">{{ next.title }}</span>
        </template>
      </template>

      <!-- A record's two actions. Both are queue operations, and they are
           different questions: Play replaces what is playing, Add does not
           disturb it. Neither is offered while the track list is still coming,
           because both of them ARE the track list. -->
      <template v-else-if="item.kind === 'album'">
        <!-- A disabled control must SAY why. Absent data and an empty record
             are different reasons, and neither of them is "no". -->
        <Btn :disabled="!tracks.length" :title="whyNoTracks" @click="queue.playAlbum(tracks)">
          ▶ Play
        </Btn>
        <Btn
          ghost
          :disabled="!tracks.length"
          :title="whyNoTracks"
          @click="queue.appendAlbum(tracks)"
        >
          Add to queue
        </Btn>
        <span v-if="whyNoTracks" class="text-dim">{{ whyNoTracks }}</span>
      </template>

      <template v-else>
        <Btn
          :disabled="!best?.available"
          :title="best?.available ? undefined : 'The machine holding this file is not answering'"
          @click="play()"
        >
          ▶ {{ resumeAt ? 'Resume' : 'Play' }}
        </Btn>
        <Btn v-if="resumeAt > 0" ghost @click="play(true)">Play from start</Btn>
        <Btn
          ghost
          small
          :disabled="busy.has(item.id)"
          :title="item.played ? 'Mark as unwatched' : 'Mark as watched without playing it'"
          @click="mark(item.id, !item.played)"
        >
          <Icon name="check" />
          {{ item.played ? 'Watched' : 'Mark watched' }}
        </Btn>
      </template>
    </DetailHead>

    <!-- A series -->
    <template v-if="item.kind === 'show'">
      <div v-if="children.isError.value" class="flex items-center gap-3">
        <p class="m-0 text-warn" role="alert">
          Could not load the episodes: {{ sentence(children.error.value) }}
        </p>
        <Btn ghost small @click="children.refetch()">Try again</Btn>
      </div>
      <p v-else-if="children.data.value && children.data.value.length === 0" class="text-dim">
        No episodes in this series yet.
      </p>

      <section v-for="season in seasons" :key="String(season)" class="mt-6">
        <div class="mb-2 flex items-baseline gap-3">
          <!-- The heading is the way into the season's own page, where the
               episodes are stills rather than rows. -->
          <h2 class="m-0">
            <button
              class="flex cursor-pointer items-baseline gap-2 text-[14px] font-[650] tracking-[0.08em] text-dim uppercase hover:text-teal"
              type="button"
              @click="openSeason(season)"
            >
              {{ seasonLabel(season, projected) }}
              <span class="text-dimmer" aria-hidden="true">→</span>
            </button>
          </h2>
          <span class="font-mono text-[12px] text-dimmer">
            {{ episodes.filter((e) => seasonOf(e, projected) === season && e.played).length }}/{{
              episodes.filter((e) => seasonOf(e, projected) === season).length
            }}
            watched
          </span>
          <button
            class="cursor-pointer text-[12px] text-dim underline hover:text-text"
            type="button"
            @click="
              markSeason(
                season,
                !episodes.filter((e) => seasonOf(e, projected) === season).every((e) => e.played),
              )
            "
          >
            {{
              episodes.filter((e) => seasonOf(e, projected) === season).every((e) => e.played)
                ? 'Mark season unwatched'
                : 'Mark season watched'
            }}
          </button>
        </div>

        <ul class="flex flex-col">
          <li
            v-for="episode in episodes.filter((e) => seasonOf(e, projected) === season)"
            :key="episode.id"
            class="flex items-center gap-2 border-b border-hairline last:border-0"
          >
            <button
              class="flex flex-1 cursor-pointer items-center gap-3 py-2 text-left hover:text-teal"
              type="button"
              @click="openItem(episode.id)"
            >
              <span class="w-16 shrink-0 font-mono text-[12px] text-dim">
                {{
                  seLabel(
                    seasonOf(episode, projected),
                    episodeOf(episode, projected),
                    episode.episode_end,
                  )
                }}
                <!-- Under a projection the file's own number is still worth
                     showing: it is what the filename says. -->
                <span v-if="projected" class="text-dimmer">#{{ episode.episode }}</span>
              </span>
              <span class="flex-1 truncate">{{ episode.title }}</span>
              <span v-if="episode.id === next?.id && !episode.played" class="chip-sand">
                next up
              </span>
              <span class="w-16 shrink-0 text-right font-mono text-[12px] text-dim">
                {{
                  !episode.played && episode.resume_position_ms && episode.resume_duration_ms
                    ? `${Math.round(watchedPct(episode) ?? 0)}% in`
                    : ''
                }}
              </span>
            </button>
            <!-- A sibling of the row's own button rather than inside it: a
                 button within a button is invalid, and a click that both
                 ticked the episode and opened it would be neither. -->
            <button
              class="shrink-0 cursor-pointer p-2"
              :class="episode.played ? 'text-teal' : 'text-dimmer hover:text-dim'"
              :disabled="busy.has(episode.id)"
              :title="episode.played ? 'Mark as unwatched' : 'Mark as watched'"
              :aria-label="`${episode.played ? 'Mark as unwatched' : 'Mark as watched'}: ${episode.title}`"
              type="button"
              @click="mark(episode.id, !episode.played)"
            >
              <Icon name="check" :size="15" />
            </button>
          </li>
        </ul>
      </section>
    </template>

    <!-- A record's track list. Pressing a track plays the RECORD from there,
         rather than that track alone: the numbered list is the record, and
         somebody pressing track 4 of nine means "start here". Adding one track
         on its own is the other button, and it levels by its own gain. -->
    <template v-else-if="item.kind === 'album'">
      <h2 class="mb-2 text-[14px] font-[650] tracking-[0.08em] text-dim uppercase">Tracks</h2>
      <div v-if="children.isError.value" class="flex items-center gap-3">
        <p class="m-0 text-warn" role="alert">
          Could not load the track list: {{ sentence(children.error.value) }}
        </p>
        <Btn ghost small @click="children.refetch()">Try again</Btn>
      </div>
      <p v-else-if="children.data.value?.length === 0" class="text-dim">
        No tracks in this record.
      </p>
      <ul v-else class="flex flex-col">
        <li
          v-for="(track, at) in tracks"
          :key="track.id"
          class="flex items-center gap-3 border-b border-hairline last:border-0"
          :class="track.id === nowPlaying && 'text-teal'"
        >
          <button
            class="flex flex-1 cursor-pointer items-center gap-3 py-1.5 text-left hover:text-teal"
            type="button"
            :aria-current="track.id === nowPlaying ? 'true' : undefined"
            :title="`Play this record from ${track.title}`"
            @click="queue.playAlbum(tracks, at)"
          >
            <!-- The playing row is marked rather than numbered: which one it is
                 matters more than where it sits. -->
            <span class="w-8 shrink-0 text-right font-mono text-[12px] text-dim">
              {{ track.id === nowPlaying ? '▶' : (track.episode ?? at + 1) }}
            </span>
            <span class="flex-1 truncate">{{ track.title }}</span>
          </button>
          <span v-if="track.played" class="flex text-teal" title="played">
            <Icon name="check" :size="13" />
          </span>
          <button
            class="cursor-pointer px-2 py-1.5 font-mono text-[11px] text-dim hover:text-teal"
            type="button"
            :aria-label="`Add ${track.title} to the queue`"
            title="Add to the queue"
            @click="queue.appendTrack(track)"
          >
            +
          </button>
        </li>
      </ul>
    </template>

    <!-- A film or an episode -->
    <template v-else>
      <section v-if="item.metadata?.cast?.length" class="mt-8">
        <h2 class="mb-2 text-[14px] font-[650] tracking-[0.08em] text-dim uppercase">Cast</h2>
        <ul class="flex flex-wrap gap-x-6 gap-y-1">
          <li v-for="person in item.metadata.cast" :key="person.name">
            {{ person.name }}
            <span v-if="person.character" class="text-dim">as {{ person.character }}</span>
          </li>
        </ul>
      </section>

      <!-- What the hub says it would do with this file, for this client. Never
           re-derived here: the point of asking the item what it would serve is
           that the answer comes from the code that will serve it. -->
      <section v-if="item.negotiated" class="mt-8">
        <h2 class="mb-2 text-[14px] font-[650] tracking-[0.08em] text-dim uppercase">
          Playback plan
        </h2>
        <div class="rounded-md border border-line bg-surface p-3">
          <div class="mb-2 flex items-center gap-3">
            <span
              class="rounded px-2 py-0.5 font-mono text-[12px] font-[650]"
              :class="`chip-${deliveryPlan(item.negotiated.cost).tone}`"
            >
              {{ deliveryPlan(item.negotiated.cost).chip }}
            </span>
            <span v-if="deliveryPlan(item.negotiated.cost).note" class="text-[13px] text-dim">
              {{ deliveryPlan(item.negotiated.cost).note }}
            </span>
            <!-- A mask left on can never be mistaken for a bug, which is the
                 whole trap this affordance would otherwise set. The panel that
                 SETS one comes with the player; the profile above already
                 reads it, so the badge cannot wait for that. -->
            <span
              v-if="masked.length"
              class="ml-auto rounded bg-warn/15 px-2 py-0.5 font-mono text-[11px] text-warn"
              title="A mask is active — this is not what your real browser would get"
            >
              masked
            </span>
          </div>
          <!-- One row per elementary stream, because that is the grain
               negotiation decides at: a file can copy its video and re-encode
               only its audio. Block-level siblings, not flex items of the
               button row below: wrapped in it they sat inline BETWEEN the two
               buttons and wrapped around them. -->
          <div
            v-for="row in [
              { label: 'video', verdict: item.negotiated.streams.video },
              { label: 'audio', verdict: item.negotiated.streams.audio },
            ]"
            :key="row.label"
            class="grid grid-cols-[80px_1fr] gap-2 font-mono text-[12px]"
          >
            <span class="text-dim">{{ row.label }}</span>
            <span v-if="row.verdict">
              <span :class="`text-${planRow(row.verdict).tone}`">
                {{ planRow(row.verdict).action }}
              </span>
              <span v-if="planRow(row.verdict).why" class="text-dim">
                — {{ planRow(row.verdict).why }}
              </span>
            </span>
          </div>
          <!-- Here, not in Settings and not only in the player: a mask takes
               effect on the NEXT session, so it has to be settable before Play
               is pressed. -->
          <div class="mt-2 flex flex-wrap items-center gap-2 border-t border-hairline pt-2">
            <Btn ghost small :aria-pressed="showCaps" @click="showCaps = !showCaps">
              client capabilities
            </Btn>
            <!-- OPS-10, and only for an admin: what the hub recorded about the
                 last session for this item, whoever played it. -->
            <Btn v-if="me.admin" ghost small @click="itemLog">Last session log</Btn>
          </div>
          <CapabilityDebug v-if="showCaps" class="mt-2" @change="maskChanged" />
        </div>
      </section>

      <!-- UI-27: grouped into works, so a film in seven numbered parts does
           not read as seven alternative encodes. -->
      <section v-if="works.length" class="mt-8">
        <h2 class="mb-2 text-[14px] font-[650] tracking-[0.08em] text-dim uppercase">
          {{ works.length === 1 ? 'Source' : 'Sources' }}
        </h2>
        <ul class="flex flex-col gap-2">
          <li
            v-for="work in works"
            :key="work.id"
            class="rounded-md border border-line bg-surface p-2"
          >
            <div v-if="work.parts.length > 1" class="mb-1 font-mono text-[11px] text-dim">
              {{ work.parts.length }} parts
              <span v-if="!work.whole" class="text-warn">
                — incomplete, {{ work.parts[0]!.parts }} expected
              </span>
            </div>
            <div
              v-for="source in work.parts"
              :key="source.path_rel"
              class="truncate font-mono text-[12px] text-dim"
            >
              {{ source.path_rel }}
            </div>
            <div class="mt-1 flex flex-wrap gap-1.5">
              <span v-if="work.parts[0]!.streams?.container" class="chip">
                {{ work.parts[0]!.streams!.container }}
              </span>
              <span
                v-for="(video, at) in work.parts[0]!.streams?.video ?? []"
                :key="`v${at}`"
                class="chip"
              >
                {{ video.codec }} {{ video.height ? `${video.height}p` : '' }}
              </span>
              <span
                v-for="(audio, at) in work.parts[0]!.streams?.audio ?? []"
                :key="`a${at}`"
                class="chip"
              >
                {{ audio.codec }}{{ audio.language ? ` ${audio.language}` : '' }}
              </span>
              <!-- One chip for the subtitles, not one per track: a file with 26
                   embedded tracks produced 26 chips all reading "text". -->
              <span
                v-if="work.parts[0]!.streams?.subtitles?.length"
                class="chip text-dim"
                :title="subtitleChipTitle(work.parts[0]!.streams!.subtitles!)"
              >
                {{ subtitleChip(work.parts[0]!.streams!.subtitles!) }}
              </span>
              <!-- Summed across the parts: one number for the work. -->
              <span class="chip text-dim">
                {{ size(work.parts.reduce((all, part) => all + part.size, 0)) }}
              </span>
              <!-- A corrected release: v2, REPACK, PROPER. Two files of the
                   same work otherwise look like the same file twice. -->
              <span v-if="work.parts[0]!.revision > 1" class="chip text-sand">
                v{{ work.parts[0]!.revision }}
              </span>
              <span v-if="work.parts.some((part) => !part.available)" class="chip text-warn">
                offline
              </span>
            </div>
          </li>
        </ul>
      </section>
      <!-- Everything this item is connected to that the providers named:
           sequels, the film a series follows, the show an episode belongs to.
           A row that is in the library is a way there; one that is not says
           so rather than offering a link to nothing. -->
      <section v-if="item.related?.length" class="mt-8">
        <h2 class="mb-2 text-[14px] font-[650] tracking-[0.08em] text-dim uppercase">Related</h2>
        <ul class="flex flex-col gap-1">
          <li v-for="link in item.related" :key="`${link.kind}-${link.title}`">
            <span class="chip text-dim">{{ link.kind.replace('_', ' ') }}</span>
            <button
              v-if="link.item_id"
              class="ml-2 cursor-pointer underline hover:text-teal"
              type="button"
              @click="openItem(link.item_id)"
            >
              {{ link.title ?? '?' }}
            </button>
            <span v-else class="ml-2 text-dim">{{ link.title ?? '?' }} (not in library)</span>
          </li>
        </ul>
      </section>
    </template>

    <SubtitlePanel
      :item="item"
      :subs="item.negotiated?.subtitles ?? []"
      :languages="subLanguages"
      :title-choice="titleChoice"
      :fps="fileFps"
      @changed="subtitlesChanged"
      @cleared="subtitlesChanged"
    />

    <Attribution :provider="item.metadata?.provider" />
  </main>
</template>

<style scoped>
@reference '../theme.css';

.chip {
  @apply rounded border border-line px-1.5 py-0.5 font-mono text-[11px];
}
.chip-sand {
  @apply rounded bg-sand/15 px-1.5 py-0.5 font-mono text-[11px] text-sand;
}
.chip-teal {
  @apply bg-teal/15 text-teal;
}
.chip-warn {
  @apply bg-warn/15 text-warn;
}
</style>

// web/src/views/Detail.tsx
import { useEffect, useMemo, useState } from 'react'
import {
  artworkUrl,
  fetchChildren,
  fetchItem,
  fetchLibraries,
  fetchPrefs,
  fetchSubtitles,
  resolveTracks,
  searchSubtitles,
  downloadSubtitle,
  deleteSubtitle,
  ocrSubtitle,
  generateRaster,
  quotaLabel,
  isImageSub,
  type SubtitleQuota,
  type Subtitle,
  type SubtitleCandidate,
  startPlaybackSession,
  isAssBurnRefusal,
  type Item,
  type ItemDetail,
  type Session,
  type Source,
  isAdmin,
  itemLogUrl,
} from '../api'
import AlbumPlayer from './AlbumPlayer'
import CapabilityDebug from './CapabilityDebug'
import { loadMask, maskSummary } from '../capabilities'
import tmdbLogo from '../assets/tmdb.svg'
import placeholder from '../assets/placeholder.svg'

const GB = 1024 * 1024 * 1024

// S01E02 for seasoned episodes; E11 for absolute numbering (anime);
// E01-02 for a batch file spanning a range.
function seLabel(season: number | null, episode: number | null, end?: number | null) {
  let e = `E${String(episode ?? 0).padStart(2, '0')}`
  if (end != null) e += `-${String(end).padStart(2, '0')}`
  return season === null ? e : `S${String(season).padStart(2, '0')}${e}`
}

function fmtDuration(ms?: number) {
  if (!ms) return null
  const m = Math.round(ms / 60000)
  return m >= 60 ? `${Math.floor(m / 60)} h ${m % 60} min` : `${m} min`
}


function Chips({ s }: { s: Source }) {
  const st = s.streams
  if (!st) return null
  return (
    <span className="chips">
      {st.container && <span className="chip">{st.container}</span>}
      {st.video?.map((v, i) => (
        <span className="chip" key={`v${i}`}>
          {v.codec} {v.height ? `${v.height}p` : ''}
        </span>
      ))}
      {st.audio?.map((a, i) => (
        <span className="chip" key={`a${i}`}>
          {a.codec}
          {a.language ? ` ${a.language}` : ''}
        </span>
      ))}
      {st.subtitles?.map((t, i) => (
        <span className="chip dim" key={`s${i}`}>
          {t.format}
        </span>
      ))}
      <span className="chip dim">{(s.size / GB).toFixed(1)} GB</span>
      {!s.available && <span className="chip warn">offline</span>}
    </span>
  )
}

export default function Detail({
  id,
  autoPlay,
  fromLib,
  onPlay,
  onOpenEpisode,
  onOpenLibrary,
}: {
  id: string
  autoPlay?: boolean
  fromLib: string
  onPlay: (item: ItemDetail, session: Session, resumeMs: number) => void
  onOpenEpisode: (id: string) => void
  onOpenLibrary: (id: string) => void
}) {
  const [item, setItem] = useState<ItemDetail | null>(null)
  const [episodes, setEpisodes] = useState<Item[]>([])
  const [animeView, setAnimeView] = useState<'seasons' | 'native'>('seasons')
  const [mediaType, setMediaType] = useState('')
  // HUB-21/24: subtitle tracks + external search results.
  const [subs, setSubs] = useState<Subtitle[]>([])
  const [subCands, setSubCands] = useState<SubtitleCandidate[] | null>(null)
  // HUB-33 subtitle-language preference for this library's media type;
  // empty = no preference, search every language.
  const [subLangs, setSubLangs] = useState<string[]>([])
  const [subBusy, setSubBusy] = useState(false)
  // HUB-32c: which image track is being OCRed (~30 s for a film).
  const [ocrBusy, setOcrBusy] = useState<string | null>(null)
  // HUB-32d: which script is being rasterised (~4 s for an episode).
  const [rasterBusy, setRasterBusy] = useState<string | null>(null)
  const [subNote, setSubNote] = useState('')
  const [subQuota, setSubQuota] = useState<SubtitleQuota | null>(null)
  const [error, setError] = useState('')
  /// Which play() call was refused for want of an ASS burn (its
  /// `fromStart`), so answering "flatten" resumes the same way. null =
  /// no question pending.
  const [assRefusal, setAssRefusal] = useState<boolean | null>(null)
  const [busy, setBusy] = useState(false)
  const [showCaps, setShowCaps] = useState(false)
  // The badge reads the stored mask, which the panel edits underneath
  // it; the counter repaints it on an edit instead of leaving the
  // previous mask on screen.
  const [capsRev, setCapsRev] = useState(0)
  const masked = useMemo(() => maskSummary(loadMask()), [capsRev])

  useEffect(() => {
    setItem(null)
    setEpisodes([])
    setSubs([])
    setSubCands(null)
    setSubNote('')
    fetchItem(id).then(setItem).catch((e) => setError(String(e)))
  }, [id])
  const reloadSubs = () =>
    fetchSubtitles(id)
      .then((r) => setSubs(r.subtitles))
      .catch(() => setSubs([]))
  useEffect(() => {
    if (item && item.kind !== 'show' && item.kind !== 'album') void reloadSubs()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [item?.id, item?.kind])
  useEffect(() => {
    if (item?.kind === 'show' || item?.kind === 'album') {
      fetchChildren(item.id)
        .then((c) => setEpisodes(c.children))
        .catch((e) => setError(String(e)))
    }
    // Library context: media type (per-type track settings, HUB-33).
    // Anime presentation (HUB-31) is purely a user preference; default
    // is the projected seasons view.
    Promise.all([fetchLibraries(), fetchPrefs().catch(() => ({ prefs: [] }))])
      .then(([l, p]) => {
        const mt = l.libraries.find((x) => x.id === fromLib)?.media_type ?? ''
        setMediaType(mt)
        const mine = p.prefs.find((x) => x.scope === '' && x.key === 'anime_view')?.value
        setAnimeView(mine === 'native' ? 'native' : 'seasons')
        setSubLangs(
          (p.prefs.find((x) => x.scope === '' && x.key === `subs.${mt}`)?.value ?? '')
            .split(',')
            .map((s) => s.trim())
            .filter(Boolean),
        )
      })
      .catch(() => {})
  }, [item?.id, item?.kind, fromLib])
  const [queueAt, setQueueAt] = useState<number | null>(null)
  // Deep-linked or history-forwarded /play URLs: start playback once
  // the item is loaded (shows have nothing to autoplay).
  const [autoPlayed, setAutoPlayed] = useState(false)
  useEffect(() => {
    if (autoPlay && !autoPlayed && item && item.kind !== 'show') {
      setAutoPlayed(true)
      const best = item.sources_detail[0]
      if (best?.available) void play()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [autoPlay, autoPlayed, item?.id])

  if (error) return <div className="error page-pad">{error}</div>
  if (!item) return null

  // Hierarchical back: episode → its series page, series/movie → the
  // library in the URL (the one we navigated from).
  const goUp = () => {
    if (item.kind === 'episode' && item.parent_id) onOpenEpisode(item.parent_id)
    else onOpenLibrary(fromLib)
  }
  const upLabel =
    item.kind === 'episode' && item.parent_id ? `← ${item.show_title ?? 'Series'}` : '← Library'

  if (item.kind === 'album') {
    const tracks = episodes // children, ordered disc/track by the API
    return (
      <main>
        <button className="btn ghost small" onClick={goUp}>
          {upLabel}
        </button>
        <div className="detail-head album-head">
          <img
            className="card-art album-art"
            src={artworkUrl(item.id, item.art_version)}
            alt=""
            onError={(e) => {
              e.currentTarget.onerror = null
              e.currentTarget.src = placeholder
            }}
          />
          <div>
            <h1>
              {item.title} {item.year && <span className="year">({item.year})</span>}
            </h1>
            <div className="detail-sub mono">
              {item.artist ?? ''} · {tracks.length} tracks
            </div>
            <div className="play-row">
              <button className="btn" disabled={!tracks.length} onClick={() => setQueueAt(0)}>
                Play album
              </button>
            </div>
          </div>
        </div>
        <ul className="rows">
          {tracks.map((t, i) => (
            <li key={t.id}>
              <button
                className={`card episode track-row${queueAt === i ? ' playing' : ''}`}
                onClick={() => setQueueAt(i)}
              >
                <span className="tno mono">{t.episode ?? i + 1}</span>
                <span>{t.title}</span>
                {t.played && <span className="seen"> ✓</span>}
              </button>
            </li>
          ))}
        </ul>
        {queueAt !== null && (
          <AlbumPlayer
            tracks={tracks}
            startAt={queueAt}
            onTrackChange={(i) => setQueueAt(i)}
            onStop={() => setQueueAt(null)}
          />
        )}
      </main>
    )
  }

  const related = item.related && item.related.length > 0 && (
    <section className="meta-block">
      <h2>Related</h2>
      <ul className="related">
        {item.related.map((r) => (
          <li key={`${r.kind}-${r.title}`}>
            <span className="chip dim">{r.kind.replace('_', ' ')}</span>{' '}
            {r.item_id ? (
              <button className="linklike" onClick={() => onOpenEpisode(r.item_id!)}>
                {r.title ?? '?'}
              </button>
            ) : (
              <span className="dim">{r.title ?? '?'} (not in library)</span>
            )}
          </li>
        ))}
      </ul>
    </section>
  )

  if (item.kind === 'show') {
    // HUB-31: absolute-numbered (anime) episodes carry a TVDB-style
    // projection; the library's anime_view picks the presentation.
    const projected =
      animeView === 'seasons' && episodes.some((e) => e.proj_season != null)
    const gSeason = (e: Item) => (projected ? e.proj_season ?? null : e.season)
    const gEpisode = (e: Item) => (projected ? e.proj_episode ?? e.episode : e.episode)
    const ordered = projected
      ? [...episodes].sort(
          (a, b) =>
            (gSeason(a) ?? 999) - (gSeason(b) ?? 999) ||
            (gEpisode(a) ?? 0) - (gEpisode(b) ?? 0),
        )
      : episodes
    // null season = absolute numbering (anime); distinct from Specials.
    const seasonLabel = (s: number | null) =>
      s === null ? (projected ? 'Other' : 'Episodes') : s === 0 ? 'Specials' : `Season ${s}`
    const seasons = [...new Set(ordered.map(gSeason))]
    // First unwatched (or in-progress) episode = the continue point.
    const next = episodes.find((e) => !e.played)
    return (
      <main>
        <button className="btn ghost small" onClick={goUp}>
          {upLabel}
        </button>
        <div className="detail-head">
          <h1>
            {item.title} {item.year && <span className="year">({item.year})</span>}
          </h1>
          <div className="detail-sub mono">
            {episodes.length} episodes
            {next && (
              <>
                {' · next: '}
                <button className="btn ghost small" onClick={() => onOpenEpisode(next.id)}>
                  {seLabel(next.season, next.episode, next.episode_end)} {next.title}
                </button>
              </>
            )}
          </div>
        </div>
        {seasons.map((s) => (
          <section key={String(s)}>
            <h2>{seasonLabel(s)}</h2>
            <ul className="rows">
              {ordered
                .filter((e) => gSeason(e) === s)
                .map((e) => (
                  <li key={e.id}>
                    <button className="card episode" onClick={() => onOpenEpisode(e.id)}>
                      <span className="mono dim">
                        E{String(gEpisode(e) ?? 0).padStart(2, '0')}
                        {e.episode_end != null &&
                          `-${String(e.episode_end).padStart(2, '0')}`}
                        {projected && <span className="dim"> #{e.episode}</span>}
                      </span>{' '}
                      {e.title}
                      {e.played && <span className="seen"> ✓</span>}
                      {!e.played && e.resume_position_ms ? (
                        <span className="dim"> · resume</span>
                      ) : null}
                    </button>
                  </li>
                ))}
            </ul>
          </section>
        ))}
        {related}
        {error && <div className="error">{error}</div>}
      </main>
    )
  }

  const best = item.sources_detail[0]
  const v = best?.streams?.video?.[0] as { fps?: [number, number] } | undefined
  const fileFps = v?.fps ? v.fps[0] / v.fps[1] : null
  const duration = best?.streams?.duration_ms
  const resumeMs =
    item.resume_position_ms && duration && item.resume_position_ms < duration * 0.9
      ? item.resume_position_ms
      : 0
  const progress = duration && resumeMs ? (resumeMs / duration) * 100 : 0

  async function findSubs(langs: string[]) {
    setSubBusy(true)
    setSubNote('')
    try {
      const r = await searchSubtitles(item!.id, langs)
      setSubCands(r.candidates)
      setSubQuota(r.quota)
      if (r.candidates.length === 0) {
        setSubNote(
          langs.length > 0
            ? `Nothing in ${langs.join(', ')} for this file.`
            : 'No subtitles found for this file.',
        )
      }
    } catch (e) {
      setSubNote(String(e))
    } finally {
      setSubBusy(false)
    }
  }

  async function play(fromStart = false, assFallback?: 'flatten') {
    setBusy(true)
    setError('')
    setAssRefusal(null)
    try {
      // Remux/transcode sessions start their pipeline at the resume
      // point (§6) — no waiting for a transcode to catch up. Direct
      // sessions resume client-side.
      const start = fromStart ? 0 : resumeMs
      // HUB-33: pick the default audio track from the user's prefs
      // (series memory > per-media-type settings), entirely client-side.
      const audio = item!.sources_detail[0]?.streams?.audio ?? []
      let audioTrack = 0
      try {
        const p = await fetchPrefs()
        audioTrack = resolveTracks(
          p.prefs,
          item!.parent_id ?? item!.id,
          item!.id,
          mediaType,
          item!.metadata?.original_language,
          audio,
        ).audioTrack
      } catch {
        // prefs unavailable → source order
      }
      // HUB-14: the hub decides the mode from the capability profile
      // (built in one shared place, mask included). start_ms is ignored
      // by the direct path server-side, so resuming needs no mode
      // prediction here.
      const session = await startPlaybackSession(item!, start, audioTrack, 0, assFallback)
      onPlay(item!, session, start)
    } catch (e) {
      // HUB-32a: nothing flattens silently. The one refusal that is a
      // question keeps the answer in hand so "flatten this time" can
      // retry from the same resume point.
      if (isAssBurnRefusal(e)) setAssRefusal(fromStart)
      else setError(String(e))
    } finally {
      setBusy(false)
    }
  }

  return (
    <main>
      <button className="btn ghost small" onClick={goUp}>
        {upLabel}
      </button>
      <div className="detail-head album-head">
        {item.kind === 'episode' && item.metadata && (
          <img
            className="card-art episode-still"
            src={artworkUrl(item.id, item.art_version)}
            alt=""
            onError={(e) => {
              e.currentTarget.onerror = null
              e.currentTarget.src = placeholder
            }}
          />
        )}
        <div>
        <h1>
          {item.kind === 'episode' && item.show_title ? `${item.show_title} · ` : ''}
          {item.kind === 'episode'
            ? `${seLabel(item.season, item.episode, item.episode_end)} · `
            : ''}
          {item.title} {item.year && <span className="year">({item.year})</span>}
        </h1>
        <div className="detail-sub mono">
          {fmtDuration(duration)}
          {item.played && <span className="seen"> · seen ×{item.play_count}</span>}
        </div>
        {progress > 0 && (
          <div className="waterline">
            <div className="waterline-fill" style={{ width: `${progress}%` }} />
          </div>
        )}
        </div>
      </div>

      {(item.metadata?.overview || item.metadata?.genres?.length) && (
        <section className="meta-block">
          {item.metadata.overview && <p className="overview">{item.metadata.overview}</p>}
          <div className="detail-sub mono">
            {item.metadata.premiered && <span>{item.metadata.premiered}</span>}
            {item.metadata.rating ? <span> · ★ {item.metadata.rating.toFixed(1)}</span> : null}
            {item.metadata.genres?.length ? (
              <span> · {item.metadata.genres.join(' · ')}</span>
            ) : null}
            {item.metadata.confidence === 'weak' && (
              <span className="dim"> · uncertain match</span>
            )}
          </div>
        </section>
      )}
      {item.metadata?.cast?.length ? (
        <section className="meta-block">
          <h2>Cast</h2>
          <ul className="cast">
            {item.metadata.cast.map((p) => (
              <li key={p.name}>
                <span>{p.name}</span>
                {p.character && <span className="dim"> as {p.character}</span>}
              </li>
            ))}
          </ul>
        </section>
      ) : null}

      <div className="play-row">
        <button className="btn" disabled={busy || !best?.available} onClick={() => play()}>
          {resumeMs ? `Resume` : 'Play'}
        </button>
        {resumeMs > 0 && (
          <button className="btn ghost" disabled={busy} onClick={() => play(true)}>
            Play from start
          </button>
        )}
        <span className="dim small-note">
          negotiated per stream — the player overlay shows the taken path
        </span>
        {/* Here, not in Settings and not only in the player: a mask
            takes effect on the NEXT session, so it has to be settable
            before this button is pressed. */}
        <button className="btn ghost small" onClick={() => setShowCaps((v) => !v)}>
          {showCaps ? 'hide caps' : 'caps'}
        </button>
        {masked.length > 0 && <span className="caps-badge mono">masked: {masked.join(' ')}</span>}
        {/* OPS-10: the LAST session for this item, whoever played it —
            the point is debugging a report from someone else, after
            they have closed the player. */}
        {isAdmin() && (
          <a className="btn ghost small" href={itemLogUrl(id)} download>
            Last session log
          </a>
        )}
      </div>
      {showCaps && <CapabilityDebug onChange={() => setCapsRev((n) => n + 1)} />}
      {assRefusal !== null && (
        <div className="error">
          No transcoder in the fleet can burn ASS subtitles, and your preference says
          burn rather than flatten.{' '}
          <button className="btn ghost small" onClick={() => void play(assRefusal, 'flatten')}>
            Flatten this time
          </button>{' '}
          <button className="btn ghost small" onClick={() => setAssRefusal(null)}>
            Stop
          </button>
        </div>
      )}
      {error && <div className="error">{error}</div>}

      {related}

      <h2>Subtitles</h2>
      {/* The player is where tracks get picked; this section is about
          managing downloads, so the file's own tracks are one line. */}
      <p className="dim">
        {(() => {
          const own = subs.filter((s) => s.origin === 'embedded' || s.origin === 'sidecar')
          if (own.length === 0) return 'No subtitles in the file.'
          const langs = [...new Set(own.map((s) => s.language ?? '?'))]
          return `${own.length} in the file: ${langs.slice(0, 12).join(', ')}${
            langs.length > 12 ? `, +${langs.length - 12} more` : ''
          }`
        })()}
      </p>
      <ul className="rows subs-list">
        {subs
          .filter(
            (s) => s.origin === 'downloaded' || s.origin === 'ocr' || s.origin === 'raster',
          )
          .map((s) => (
            <li key={s.id}>
              <span className="chips">
                {/* "ocr" stays visible: machine-read text is imperfect
                    by nature and must say so (HUB-32c). */}
                <span className="chip">{s.origin}</span>
                <span>{s.language ?? '?'} · {s.format}</span>
              </span>
              <button
                className="btn ghost small"
                onClick={() =>
                  deleteSubtitle(s.id)
                    .then(reloadSubs)
                    .catch((e) => setError(String(e)))
                }
              >
                Remove
              </button>
            </li>
          ))}
        {/* HUB-32c: image tracks with no OCR text derived from them
            yet can grow one — per stream, keyed by lineage, so two
            same-language image tracks each get their own button. */}
        {subs
          .filter(
            (s) =>
              isImageSub(s) &&
              (s.origin === 'embedded' || s.origin === 'sidecar') &&
              !subs.some((t) => t.origin === 'ocr' && t.derived_from === s.id),
          )
          .map((s) => (
            <li key={`ocr-${s.id}`}>
              <span className="chips">
                <span className="chip dim">{s.format}</span>
                <span>{s.language ?? '?'} · image only</span>
              </span>
              <button
                className="btn ghost small"
                disabled={ocrBusy !== null}
                onClick={() => {
                  setOcrBusy(String(s.id))
                  ocrSubtitle(s.id)
                    .then(reloadSubs)
                    .catch((e) => setError(String(e)))
                    .finally(() => setOcrBusy(null))
                }}
              >
                {ocrBusy === String(s.id) ? 'Reading…' : '→ text (OCR)'}
              </button>
            </li>
          ))}
        {/* HUB-32d: styled scripts with no rasterised overlay derived
            from them yet. Same shape as the OCR button and the same
            lineage rule, but the opposite direction — OCR turns
            pictures into text, this turns text into pictures so a
            client that cannot render ASS still sees the typesetting
            without anyone encoding video. */}
        {subs
          .filter(
            (s) =>
              ['ass', 'ssa'].includes(s.format) &&
              (s.origin === 'embedded' || s.origin === 'sidecar') &&
              !subs.some((t) => t.origin === 'raster' && t.derived_from === s.id),
          )
          .map((s) => (
            <li key={`raster-${s.id}`}>
              <span className="chips">
                <span className="chip dim">{s.format}</span>
                <span>{s.language ?? '?'} · styled</span>
              </span>
              <button
                className="btn ghost small"
                disabled={rasterBusy !== null}
                title="render to an overlay track for clients without an ASS renderer"
                onClick={() => {
                  setRasterBusy(String(s.id))
                  generateRaster(s.id)
                    .then(reloadSubs)
                    .catch((e) => setError(String(e)))
                    .finally(() => setRasterBusy(null))
                }}
              >
                {rasterBusy === String(s.id) ? 'Rendering…' : '→ overlay (typeset)'}
              </button>
            </li>
          ))}
      </ul>
      <div className="row-form">
        <button
          className="btn ghost small"
          disabled={subBusy}
          onClick={() => void findSubs(subLangs)}
        >
          {subBusy
            ? 'Searching…'
            : subLangs.length > 0
              ? `Find subtitles (${subLangs.join(', ')})`
              : 'Find subtitles online'}
        </button>
        {/* The language filter comes from Settings → this media type;
            offer the unfiltered search when it finds nothing. */}
        {subLangs.length > 0 && subCands?.length === 0 && !subBusy && (
          <button className="btn ghost small" onClick={() => void findSubs([])}>
            Search all languages
          </button>
        )}
        {subNote && <span className="dim">{subNote}</span>}
        {quotaLabel(subQuota) && <span className="dim mono">{quotaLabel(subQuota)}</span>}
      </div>
      {subCands && subCands.length > 0 && (
        <ul className="rows sub-candidates">
          {subCands.slice(0, 25).map((c) => (
            <li key={c.file_id}>
              <span className="chips">
                {c.hash_match && (
                  <span className="chip" title="the provider has this exact file's hash on this subtitle">
                    hash
                  </span>
                )}
                <span className="chip dim">{c.language ?? '?'}</span>
                <span>{c.release_name ?? '(no name)'}</span>
                <span className="dim mono">{c.downloads} dl</span>
                {c.rating ? <span className="dim mono">★ {c.rating.toFixed(1)}</span> : null}
                {c.uploader && <span className="dim">by {c.uploader}</span>}
                {/* fps mismatch is the classic cause of progressive drift */}
                {c.fps && fileFps && Math.abs(c.fps - fileFps) > 0.1 ? (
                  <span className="chip warn" title={`timed for ${c.fps} fps; this file is ${fileFps.toFixed(3)} fps`}>
                    {c.fps} fps
                  </span>
                ) : null}
              </span>
              <button
                className="btn small"
                disabled={subBusy}
                onClick={() => {
                  setSubBusy(true)
                  downloadSubtitle(item.id, c.file_id, c.language)
                    .then((r) => {
                      setSubQuota(r.quota)
                      setSubNote('Downloaded — available as a subtitle track.')
                      setSubCands(null)
                      return reloadSubs()
                    })
                    .catch((e) => setSubNote(String(e)))
                    .finally(() => setSubBusy(false))
                }}
              >
                Download
              </button>
            </li>
          ))}
        </ul>
      )}

      <h2>Sources</h2>
      <ul className="sources">
        {item.sources_detail.map((s) => (
          <li key={s.path_rel}>
            <span className="path mono">{s.path_rel}</span>
            {s.revision > 1 && (
              <span className="chip" title="corrected release (v2 / REPACK / PROPER)">
                v{s.revision}
              </span>
            )}
            <Chips s={s} />
          </li>
        ))}
      </ul>
      {item.metadata?.provider === 'tmdb' && (
        <footer className="tmdb-attrib">
          <img src={tmdbLogo} alt="TMDB" />
          <span>
            This product uses TMDB and the TMDB APIs but is not endorsed, certified, or
            otherwise approved by TMDB.
          </span>
        </footer>
      )}
      {item.metadata?.provider === 'musicbrainz' && (
        <footer className="tmdb-attrib">
          <span>Metadata from MusicBrainz; cover art from the Cover Art Archive.</span>
        </footer>
      )}
      {item.metadata?.provider === 'anilist' && (
        <footer className="tmdb-attrib">
          <span>Metadata from AniList and AniDB.</span>
        </footer>
      )}
      {item.metadata?.provider === 'tvdb' && (
        <footer className="tmdb-attrib">
          <span>Metadata provided by TheTVDB. Please consider contributing missing data.</span>
        </footer>
      )}
    </main>
  )
}
