// web/src/views/Settings.vue
<script setup lang="ts">
/// Your settings. Everything here saves the moment you change it, which is
/// why every control is optimistic and every failure puts the value back —
/// see `useOptimistic`, which is where the hard part is.
import { computed, ref, watch } from 'vue'

import Btn from '../components/Btn.vue'
import Failed from '../components/Failed.vue'
import Icon from '../components/Icon.vue'
import Ordered from '../components/Ordered.vue'
import {
  ASS_RUNGS,
  assLadder,
  bandwidthValue,
  ORIGINAL,
  stored,
  suggestions,
  validToken,
  wishlist,
} from '../domain/prefs.ts'
import { addAbove, moved } from '../domain/reorder.ts'
import { notify } from '../composables/notices.ts'
import { putPref, usePrefs } from '../composables/prefs.ts'
import { sentence } from '../domain/refusal.ts'
import { useOptimistic } from '../composables/optimistic.ts'

/// Per media type, because what you want from a film is not what you want
/// from anime — HUB-33.
const MEDIA_TYPES = ['movies', 'series', 'anime'] as const

const { query, values, known } = usePrefs()

/// The screen's own copy, seeded from the server's answer and edited in place.
/// An optimistic control needs somewhere to hold a value the server has not
/// confirmed, and a value put back has to land somewhere too.
watch(known, (fresh) => (values.value = { ...fresh }), { immediate: true })

const saved = ref(false)
let flashTimer: ReturnType<typeof setTimeout> | undefined
function flash() {
  saved.value = true
  clearTimeout(flashTimer)
  flashTimer = setTimeout(() => (saved.value = false), 1200)
}

/// One optimistic writer per key. They must not share a revert target: two
/// controls failing at once would put each other's values back.
const writers = new Map<string, ReturnType<typeof useOptimistic<string>>>()
function writerFor(key: string) {
  const held = writers.get(key)
  if (held) return held
  const made = useOptimistic(
    computed({
      get: () => values.value[key] ?? '',
      set: (next: string) => (values.value = { ...values.value, [key]: next }),
    }),
  )
  writers.set(key, made)
  return made
}

async function save(key: string, next: string) {
  const ok = await writerFor(key).put(next, () => putPref('', key, next))
  if (ok) flash()
}

/// A wishlist, as the list the controls work on.
function listFor(kind: 'audio' | 'subs', mediaType: string): string[] {
  return wishlist(values.value[`${kind}.${mediaType}`] ?? '', kind)
}
function saveList(kind: 'audio' | 'subs', mediaType: string, items: string[]) {
  void save(`${kind}.${mediaType}`, stored(items))
}

const typing = ref<Record<string, string>>({})
const rejected = ref<Record<string, boolean>>({})

function add(kind: 'audio' | 'subs', mediaType: string) {
  const field = `${kind}.${mediaType}`
  const token = (typing.value[field] ?? '').trim().toLowerCase()
  if (!validToken(token)) {
    rejected.value = { ...rejected.value, [field]: true }
    return
  }
  const items = listFor(kind, mediaType)
  if (items.includes(token)) {
    // Already there: nothing to save, and nothing to complain about either.
    typing.value = { ...typing.value, [field]: '' }
    return
  }
  rejected.value = { ...rejected.value, [field]: false }
  typing.value = { ...typing.value, [field]: '' }
  // Above the backstop, wherever it sits — a language added after it is never
  // reached, and the setting silently does nothing.
  saveList(kind, mediaType, addAbove(items, token, ORIGINAL))
}

function move(kind: 'audio' | 'subs', mediaType: string, from: number, to: number) {
  const next = moved(listFor(kind, mediaType), from, to)
  if (next) saveList(kind, mediaType, next)
}

function remove(kind: 'audio' | 'subs', mediaType: string, at: number) {
  const items = listFor(kind, mediaType)
  saveList(
    kind,
    mediaType,
    items.filter((_, n) => n !== at),
  )
}

/// The bandwidth box keeps its own copy, so a refusal can put the old value
/// back. Stored as the server stores it: no cap is an empty string, not "0",
/// or the local copy disagrees with the hub about the same key.
const bandwidth = ref('')
watch(
  () => values.value['bandwidth_kbps'],
  (v) => (bandwidth.value = v ?? ''),
  { immediate: true },
)

/// Read off the field rather than off the model: the box is the only control
/// here that is not committed on every keystroke, and one binding fewer
/// between what was typed and what is saved is one fewer thing to be stale.
async function saveBandwidth(typed: string) {
  bandwidth.value = typed
  const next = bandwidthValue(typed.trim() === '0' ? '' : typed)
  if (next === null) {
    notify('That is not a number of kbit/s.')
    bandwidth.value = values.value['bandwidth_kbps'] ?? ''
    return
  }
  if (next === (values.value['bandwidth_kbps'] ?? '')) return
  await save('bandwidth_kbps', next)
  bandwidth.value = values.value['bandwidth_kbps'] ?? ''
}

const ladder = computed(() => assLadder(values.value['subs.ass'] ?? ''))
function moveRung(from: number, to: number) {
  const next = moved(ladder.value, from, to)
  if (next) void save('subs.ass', stored(next))
}

/// HUB-31: which numbering an absolute-numbered series is shown in. The two
/// sides of one control — the title on each says what the word means, because
/// "native" does not say it on its own.
const ANIME_VIEWS = [
  { value: 'seasons', title: 'TVDB-style seasons (projected)' },
  { value: 'native', title: 'flat absolute numbering (AniDB-native)' },
] as const
/// HUB-31: which numbering an absolute-numbered series is shown in.
const animeView = computed(() => (values.value['anime_view'] === 'native' ? 'native' : 'seasons'))

/// Clicking a language makes it the first choice — the one-press version of a
/// drag, and the reason the name is a button.
function promote(kind: 'audio' | 'subs', mediaType: string, at: number) {
  const items = listFor(kind, mediaType)
  const picked = items[at]
  if (!picked) return
  saveList(kind, mediaType, [picked, ...items.filter((_, n) => n !== at)])
}

/// HUB-21. Subtitle search works without an account, on a download budget the
/// whole server shares; attaching your own spends your own instead.
///
/// The two writes are settled independently. Reporting one flat failure for a
/// half-save left the hub holding the new username while the card still showed
/// the old one — and the badge still reading "shared budget" for an account
/// that was half attached.
const osUser = ref('')
const osPass = ref('')
const osBusy = ref(false)
watch(
  () => values.value['opensubtitles.username'],
  (name) => (osUser.value = name ?? ''),
  { immediate: true },
)
const osAttached = computed(
  () => !!values.value['opensubtitles.username'] || !!values.value['opensubtitles.password'],
)

/// Its own function, not two statements in the template: a multi-statement
/// inline handler parses nowhere except by accident.
function disconnect() {
  osUser.value = ''
  void saveAccount('', '')
}

async function saveAccount(user: string, pass: string) {
  osBusy.value = true
  try {
    const [name, secret] = await Promise.allSettled([
      putPref('', 'opensubtitles.username', user),
      putPref('', 'opensubtitles.password', pass),
    ])
    osPass.value = ''
    // Whatever landed is what the hub has, so the card must show that.
    values.value = {
      ...values.value,
      'opensubtitles.username':
        name.status === 'fulfilled' ? user : (values.value['opensubtitles.username'] ?? ''),
      'opensubtitles.password': secret.status === 'fulfilled' ? pass : '',
    }
    const failed = [
      name.status === 'rejected' ? 'username' : null,
      secret.status === 'rejected' ? 'password' : null,
    ].filter(Boolean)
    if (failed.length === 0) flash()
    else notify(`Could not save the ${failed.join(' or ')}.`)
  } finally {
    osBusy.value = false
  }
}
</script>

<template>
  <!-- A failed load used to render the page anyway, with every control showing
       its default — which reads as "these are your settings" when the truth is
       "we have no idea what your settings are". Worse than a blank screen,
       because the next thing you do is change one. -->
  <Failed
    v-if="query.isError.value"
    what="Could not load your settings."
    :message="sentence(query.error.value)"
    @retry="query.refetch()"
  />

  <main v-else-if="query.data.value">
    <div class="mb-1 flex items-baseline gap-3">
      <h1 class="text-[22px] font-[650] tracking-[0.01em]">Settings</h1>
      <!-- Always in the layout, only sometimes visible: a chip that appears
           would shift the heading every time you changed something. -->
      <span
        class="rounded px-1.5 py-0.5 font-mono text-[11px] text-teal transition-opacity"
        :class="saved ? 'opacity-100' : 'opacity-0'"
        role="status"
      >
        saved
      </span>
    </div>
    <p class="mb-3 text-dim">Everything here saves the moment you change it.</p>

    <!-- One column, one measure. Cards 12px apart rather than 24, so the page
         reads as a stack of related settings and not as separate screens. -->
    <div class="flex max-w-[660px] flex-col gap-3">
      <!-- HUB-21. Works without an account; attaching one spends your own
           download budget instead of the server's shared one. -->
      <section class="flex flex-col gap-3 rounded-md border border-line bg-surface px-4 py-3.5">
        <div class="flex items-center gap-2">
          <span class="flex text-teal"><Icon name="download" :size="15" /></span>
          <span class="text-[14px] leading-none font-[600] capitalize">OpenSubtitles</span>
        </div>
        <p class="m-0 max-w-[560px] text-[12.5px] text-dim">
          Subtitle search works without an account, on a small download budget shared by everyone on
          this server. Attach your own opensubtitles.com account to spend your own budget instead.
          Subtitles you download are shared with everyone here.
        </p>
        <div class="flex flex-wrap items-center gap-x-2.5 gap-y-2">
          <label class="w-[76px] shrink-0 font-mono text-[12px] text-dim" for="os-user">
            account
          </label>
          <input
            id="os-user"
            v-model="osUser"
            class="min-w-[150px] flex-[1_1_170px] rounded border border-line bg-bg px-2 py-1"
            placeholder="opensubtitles.com username"
          />
          <label class="sr-only" for="os-pass">opensubtitles.com password</label>
          <input
            id="os-pass"
            v-model="osPass"
            class="min-w-[150px] flex-[1_1_170px] rounded border border-line bg-bg px-2 py-1"
            type="password"
            :placeholder="
              values['opensubtitles.password'] ? 'password saved — enter to replace' : 'password'
            "
          />
          <Btn
            small
            :disabled="osBusy || !osUser.trim() || !osPass.trim()"
            @click="saveAccount(osUser.trim(), osPass)"
          >
            Save
          </Btn>
          <Btn v-if="osAttached" ghost small :disabled="osBusy" @click="disconnect">
            Disconnect
          </Btn>
        </div>
      </section>

      <section class="flex flex-col gap-3 rounded-md border border-line bg-surface px-4 py-3.5">
        <div class="flex items-center gap-2">
          <span class="flex text-teal"><Icon name="play" :size="15" /></span>
          <span class="text-[14px] leading-none font-[600] capitalize">Playback</span>
        </div>
        <p class="m-0 max-w-[560px] text-[12.5px] text-dim">
          Applies wherever you play, on this account.
        </p>

        <div class="flex flex-wrap items-center gap-x-2.5 gap-y-2">
          <label class="w-[76px] shrink-0 font-mono text-[12px] text-dim" for="bandwidth">
            bandwidth
          </label>
          <!-- Shares the line rather than taking one: a fixed width here left
               the field two thirds empty beside a placeholder it could not
               show. -->
          <input
            id="bandwidth"
            v-model="bandwidth"
            class="min-w-[150px] flex-[1_1_170px] rounded border border-line bg-bg px-2 py-1 font-mono"
            type="number"
            min="0"
            placeholder="kbit/s cap (0 = none)"
            @blur="saveBandwidth(($event.target as HTMLInputElement).value)"
          />
        </div>
        <!-- An explanation belongs under the control it explains, lined up
             with it: 76px of label plus the 10px gap. -->
        <p class="mt-[-2px] ml-[86px] max-w-[480px] text-[12px] text-dim">
          A ceiling for how much data playback may use — worth setting on a metered or slow
          connection. Anything above it is re-encoded smaller; a file that cannot be re-encoded will
          refuse to play rather than stall. Leave it empty for no limit.
        </p>
      </section>

      <section class="flex flex-col gap-3 rounded-md border border-line bg-surface px-4 py-3.5">
        <!-- Not a card NAME: those are capitalised because they are proper
             nouns and media types. This is a sentence, and `capitalize` was
             rendering it "Styled Subtitles". -->
        <span class="text-[12.5px] font-[600]">Styled subtitles</span>
        <p class="m-0 max-w-[560px] text-[12.5px] text-dim">
          How styled subtitles reach a player that cannot draw them itself, in the order to try. The
          server takes the first rung this client and this server can actually serve.
        </p>
        <!-- `fixed`: the order expresses priority, never removal. Every rung is
             always present, so a ✕ on each one offered something that does not
             exist (owner decision, 2026-08-03). -->
        <Ordered
          :items="ladder"
          fixed
          label="Styled subtitle fallbacks, in order"
          :display="(rung) => ASS_RUNGS[rung as keyof typeof ASS_RUNGS].name"
          :note="(rung) => ASS_RUNGS[rung as keyof typeof ASS_RUNGS].note"
          @move="moveRung"
        />
      </section>

      <!-- Which tracks to start with, per media type: what you want from a
           film is not what you want from anime (HUB-33). -->
      <div class="mt-1">
        <span class="text-[12.5px] font-[600]">Which tracks to start with</span>
        <p class="m-0 mt-2 max-w-[560px] text-[12.5px] text-dim">
          When you open something, the first language in each list that the file actually has is the
          one that plays. Drag a language to move it, or click it to make it your first choice.
          <span class="font-mono text-teal">original</span> means whatever language the title was
          made in. Picking a different track while watching only affects that title, and it wins
          over these.
        </p>
      </div>

      <section
        v-for="mediaType in MEDIA_TYPES"
        :key="mediaType"
        class="flex flex-col gap-3 rounded-md border border-line bg-surface px-4 py-3.5"
      >
        <div class="flex items-center gap-2">
          <span class="flex text-teal">
            <Icon :name="mediaType === 'movies' ? 'movie' : 'show'" :size="15" />
          </span>
          <span class="text-[14px] leading-none font-[600] capitalize">{{ mediaType }}</span>
        </div>

        <!-- Anime's presentation first: it decides how the episode lists on
             every other screen are numbered, which is a bigger difference than
             a track order. -->
        <template v-if="mediaType === 'anime'">
          <div class="flex flex-wrap items-center gap-x-2.5 gap-y-2">
            <span id="anime-view" class="w-[76px] shrink-0 font-mono text-[12px] text-dim">
              view
            </span>
            <!-- A two-state choice reads as one control, not two chips. The
                 unpicked side keeps full-strength text: dimming it is how a
                 disabled control looks, and it is not disabled — it is the
                 other half of the choice. -->
            <span class="flex flex-wrap gap-1.5" role="group" aria-labelledby="anime-view">
              <button
                v-for="option in ANIME_VIEWS"
                :key="option.value"
                class="inline-flex min-h-7 cursor-pointer items-center rounded border px-[11px] py-1 font-mono text-[12px] tracking-[0.02em]"
                :class="
                  animeView === option.value
                    ? 'border-teal bg-teal font-[600] text-bg'
                    : 'border-dim bg-surface text-text hover:border-prose hover:bg-hover'
                "
                type="button"
                :aria-pressed="animeView === option.value"
                :title="option.title"
                @click="save('anime_view', option.value)"
              >
                {{ option.value }}
              </button>
            </span>
          </div>
          <p class="mt-[-2px] ml-[86px] max-w-[480px] text-[12px] text-dim">
            {{
              animeView === 'seasons'
                ? 'Numbered in seasons, the way most people know these shows.'
                : 'Numbered straight through, the way they were broadcast.'
            }}
          </p>
        </template>

        <!-- Label, pills and the way to add one, all on the same line — a
             language is a word, and a dozen of them belong in a row. -->
        <div
          v-for="kind in ['audio', 'subs'] as const"
          :key="kind"
          class="flex flex-wrap items-center gap-x-2.5 gap-y-2"
        >
          <span class="w-[76px] shrink-0 font-mono text-[12px] text-dim">
            {{ kind === 'audio' ? 'audio' : 'subtitles' }}
          </span>
          <span
            v-if="listFor(kind, mediaType).length === 0"
            class="flex min-h-[1.6rem] flex-[1_1_240px] items-center text-[12px] text-dimmer"
          >
            no subtitles
          </span>
          <!-- The pills take the slack, which is what puts the add box against
               the right edge of the row rather than against the last pill. -->
          <Ordered
            v-else
            chips
            class="min-h-[1.6rem] flex-[1_1_240px]"
            :items="listFor(kind, mediaType)"
            :label="`${kind === 'audio' ? 'Audio' : 'Subtitle'} languages for ${mediaType}, in order`"
            :pinned="kind === 'audio' ? [ORIGINAL] : []"
            @move="(from, to) => move(kind, mediaType, from, to)"
            @remove="(at) => remove(kind, mediaType, at)"
            @promote="(at) => promote(kind, mediaType, at)"
          />
          <label class="sr-only" :for="`${kind}-${mediaType}`">
            Add a language for {{ mediaType }}
          </label>
          <!-- Dashed, because it is an opening rather than a value. -->
          <input
            :id="`${kind}-${mediaType}`"
            v-model="typing[`${kind}.${mediaType}`]"
            class="w-[70px] flex-none rounded border border-dashed bg-bg px-2 py-1 font-mono text-[12px]"
            :class="rejected[`${kind}.${mediaType}`] ? 'border-warn' : 'border-line'"
            :aria-invalid="rejected[`${kind}.${mediaType}`] || undefined"
            :list="`langs-${kind}-${mediaType}`"
            placeholder="add…"
            @keydown.enter.prevent="add(kind, mediaType)"
            @blur="typing[`${kind}.${mediaType}`]?.trim() && add(kind, mediaType)"
          />
          <datalist :id="`langs-${kind}-${mediaType}`">
            <option
              v-for="token in suggestions(listFor(kind, mediaType), kind)"
              :key="token"
              :value="token"
            />
          </datalist>
          <span v-if="rejected[`${kind}.${mediaType}`]" class="text-[12px] text-warn" role="alert">
            Two or three letters, like “en” or “nld”.
          </span>
        </div>
      </section>
    </div>
  </main>
</template>

// web/src/views/Settings.tsx
import { useEffect, useRef, useState } from 'react'
import { fetchPrefs, putPref } from '../api'
import { notify } from '../toast'
import { addAbove, moved, useDragOrder } from '../reorder'
import Icon from '../icons'
import Failed from '../Failed'

// HUB-33 per-media-type track defaults, stored as user-global prefs:
// key `audio.{type}` / `subs.{type}` = ordered language list ('original'
// allowed for audio). Every mutation saves immediately; per-series
// manual choices still outrank these.
const MEDIA_TYPES = ['movies', 'series', 'anime'] as const

const SUGGEST = [
  'original',
  'en',
  'nl',
  'ja',
  'de',
  'fr',
  'es',
  'it',
  'pt',
  'sv',
  'da',
  'no',
  'fi',
  'pl',
  'ru',
  'zh',
  'ko',
]
const TOKEN = /^(original|[a-z]{2,3})$/

/// An optimistic write that can be put back.
///
/// Reverting to `value` reverts to the prop from the closure that made the
/// request. Two changes in quick succession — a drag, then another before the
/// first answers — and a failure of the older one drags the list back past a
/// change that was saved. So the revert target is the last value the server
/// actually confirmed, and only the newest write is allowed to use it.
function useOptimistic(value: string, onChange: (v: string) => void, flash: () => void) {
  const seq = useRef(0)
  const inflight = useRef(0)
  const saved = useRef(value)
  /// Which write `saved` came from. `putPref` guarantees replies land in this
  /// order too; the sequence still decides whether a failure is current enough
  /// to put anything back on screen.
  const savedSeq = useRef(0)
  // Nothing outstanding means the prop is what the server has.
  if (inflight.current === 0) saved.current = value
  return (v: string, put: () => Promise<unknown>) => {
    const mine = ++seq.current
    inflight.current++
    onChange(v)
    // `putPref` serialises whole-state commits per preference key. The
    // optimistic control still moves now; only its network writes wait.
    put()
      .then(() => {
        // Any success moves the revert target, not just the newest one. Only
        // advancing it for the newest meant an older write succeeding while a
        // newer one was still out left the target at the value from BEFORE
        // both — so when the newer one then failed, the revert went back past
        // a change the server had accepted and kept.
        if (mine > savedSeq.current) {
          savedSeq.current = mine
          saved.current = v
        }
        flash()
      })
      .catch(() => {
        if (mine !== seq.current) return
        onChange(saved.current)
        notify('Could not save that — put back the way it was.')
      })
      .finally(() => {
        inflight.current--
      })
  }
}

function LangChips({
  mediaType,
  kind,
  value,
  onChange,
  flash,
}: {
  mediaType: string
  kind: 'audio' | 'subs'
  value: string
  onChange: (v: string) => void
  flash: () => void
}) {
  // 'original' is the permanent audio backstop: always in the list,
  // not removable (reorderable — others may be preferred above it).
  const stored = value ? value.split(',') : []
  const items = kind === 'audio' && !stored.includes('original') ? [...stored, 'original'] : stored
  const [entry, setEntry] = useState('')
  const [bad, setBad] = useState(false)
  const inputRef = useRef<HTMLInputElement>(null)

  /// Show the new order first, then save it. Waiting for the round trip
  /// meant the pills still read the old order while the request was out, so
  /// a second drag in that window computed its move from the stale list and
  /// wrote it back — losing whatever the first drag had just done.
  const write = useOptimistic(value, onChange, flash)
  const commit = (list: string[]) => {
    const v = list.join(',')
    write(v, () => putPref('', `${kind}.${mediaType}`, v))
  }

  const add = () => {
    const t = entry.trim().toLowerCase()
    if (!t) return
    if (!TOKEN.test(t) || (kind === 'subs' && t === 'original') || items.includes(t)) {
      setBad(true)
      return
    }
    setBad(false)
    setEntry('')
    // Immediately before the pinned backstop, wherever it sits. `resolveTracks`
    // takes the FIRST language the file has, and `original` matches almost
    // every file — so appending after it persisted "original,nl" and the
    // language just added never applied, under a "saved" flash and a tooltip
    // calling original the final fallback. Inserted rather than appended-after-
    // filtering, because `original` is reorderable on purpose: moving it to the
    // end would rewrite an order the viewer had chosen.
    commit(addAbove(items, t, 'original'))
  }

  const listId = `langs-${kind}-${mediaType}`
  const drag = useDragOrder((from, to) => {
    const next = moved(items, from, to)
    if (next) commit(next)
  })

  return (
    <div className="pref-row">
      <span className="pref-label mono">{kind === 'subs' ? 'subtitles' : kind}</span>
      <span className="chips">
        {items.length === 0 && <span className="dimmer">no subtitles</span>}
        {items.map((l, i) => {
          const pinned = kind === 'audio' && l === 'original'
          return (
            <span
              key={l}
              className={`lang-pill${drag.look(i)}`}
              title="Drag to reorder, or click to make it the first choice"
              {...drag.row(i)}
            >
              <span className="lang-grip" aria-hidden="true">
                <Icon name="grip" size={10} />
              </span>
              {/* Click still promotes: a drag is a pointer gesture, and the
                  keyboard has to be able to reach the same outcome. */}
              <button
                className="lang-name mono"
                title={i === 0 ? 'first choice' : 'make it the first choice'}
                onClick={() => i > 0 && commit([l, ...items.filter((x) => x !== l)])}
              >
                {l}
              </button>
              {pinned ? (
                <span className="lang-end lang-lock" title="always the final fallback">
                  <Icon name="lock" size={10} />
                </span>
              ) : (
                <button
                  className="lang-end chip-x"
                  title={`remove ${l}`}
                  /* Says what it did. It is one click, it sits next to a drag
                     handle, and a silently shorter list is not something you
                     notice until a film starts in the wrong language. */
                  onClick={() => {
                    commit(items.filter((x) => x !== l))
                    notify(
                      `Removed ${l} from ${kind === 'subs' ? 'subtitles' : kind} for ${mediaType}.`,
                    )
                  }}
                >
                  ×
                </button>
              )}
            </span>
          )
        })}
      </span>
      <input
        ref={inputRef}
        className={`lang-add${bad ? ' invalid' : ''}`}
        placeholder="add…"
        list={listId}
        value={entry}
        onChange={(e) => {
          setEntry(e.target.value)
          setBad(false)
        }}
        onKeyDown={(e) => e.key === 'Enter' && add()}
        onBlur={() => entry.trim() && add()}
      />
      <datalist id={listId}>
        {SUGGEST.filter((s) => !items.includes(s) && !(kind === 'subs' && s === 'original')).map(
          (s) => (
            <option key={s} value={s} />
          ),
        )}
      </datalist>
    </div>
  )
}

function OpenSubtitlesAccount({
  username,
  hasPassword,
  onSaved,
  flash,
}: {
  username: string
  hasPassword: boolean
  onSaved: (username: string, password: string) => void
  flash: () => void
}) {
  const [user, setUser] = useState(username)
  const [pass, setPass] = useState('')
  const [busy, setBusy] = useState(false)
  useEffect(() => setUser(username), [username])

  const save = (u: string, p: string) => {
    setBusy(true)
    // `allSettled`, because these are two independent writes and reporting a
    // flat failure for a half-save left the hub holding the new username while
    // the card still showed the old one — and the badge still read "shared
    // budget" for an account that was half attached.
    Promise.allSettled([
      putPref('', 'opensubtitles.username', u),
      putPref('', 'opensubtitles.password', p),
    ])
      .then(([un, pw]) => {
        const failed = [
          un.status === 'rejected' ? 'username' : null,
          pw.status === 'rejected' ? 'password' : null,
        ].filter(Boolean)
        setPass('')
        // Whatever landed is what the hub has, so the card must show that.
        onSaved(un.status === 'fulfilled' ? u : username, pw.status === 'fulfilled' ? p : '')
        if (failed.length === 0) flash()
        else notify(`Could not save the ${failed.join(' or ')}.`)
      })
      .finally(() => setBusy(false))
  }

  return (
    <div className="row-form pref-row">
      <span className="pref-label mono">account</span>
      <input
        placeholder="opensubtitles.com username"
        value={user}
        onChange={(e) => setUser(e.target.value)}
      />
      <input
        type="password"
        placeholder={hasPassword ? 'password saved — enter to replace' : 'password'}
        value={pass}
        onChange={(e) => setPass(e.target.value)}
      />
      <button
        className="btn small"
        disabled={busy || !user.trim() || !pass.trim()}
        onClick={() => save(user.trim(), pass)}
      >
        Save
      </button>
      {(username || hasPassword) && (
        <button
          className="btn ghost small"
          disabled={busy}
          onClick={() => {
            setUser('')
            save('', '')
          }}
        >
          Disconnect
        </button>
      )}
    </div>
  )
}

/// The HUB-32a/d fallback ladder: reorder with the arrows. Every rung
/// is always present — the order expresses priority, never removal, so
/// there is always something a client can be served (owner decision,
/// 2026-08-03).
///
/// Named for what the viewer gets, not for the mechanism: the setting is
/// worth having only if you can tell which one you would rather watch.
const ASS_RUNGS = {
  flatten: {
    name: 'plain text',
    note: 'fonts, colours and positions dropped. Works anywhere, costs nothing.',
  },
  overlay: {
    name: 'drawn on top',
    note: 'the server draws the styling and sends it as its own layer. Looks right, and the picture is untouched.',
  },
  burn: {
    name: 'burnt into the picture',
    note: 'exactly as the author made it, but the video has to be re-encoded to carry it.',
  },
} as const
type AssRung = keyof typeof ASS_RUNGS

function AssLadder({
  value,
  onChange,
  flash,
}: {
  value: string
  onChange: (v: string) => void
  flash: () => void
}) {
  const all = Object.keys(ASS_RUNGS) as AssRung[]
  // A permutation, always: whatever the stored value leaves out is
  // appended, mirroring the server's own parse.
  const parsed = value
    .split(',')
    .map((s) => s.trim())
    .filter((s): s is AssRung => (all as string[]).includes(s))
  const order = [...new Set([...parsed, ...all])]
  const write = useOptimistic(value, onChange, flash)
  const save = (next: AssRung[]) => {
    const v = next.join(',')
    write(v, () => putPref('', 'ass_order', v))
  }
  const move = (from: number, to: number) => {
    const next = moved(order, from, to)
    if (next) save(next)
  }
  const drag = useDragOrder(move)
  return (
    <div className="pref-block">
      <div className="pref-block-head">Subtitles with their own styling</div>
      <p className="dim card-prose">
        Some subtitles carry fonts, colours and on-screen positions — signs, songs, anything
        typeset. A player that can draw them itself always does, and this browser can, so this order
        only decides what happens on players that cannot. The first one that player and this server
        can both manage is what gets used.
      </p>
      <ol className="ladder">
        {order.map((r, i) => (
          <li
            key={r}
            className={drag.look(i).trim()}
            title="Drag to reorder"
            /* No arrow buttons: the grip says what to do and two more
               controls per row said it again, louder. The row itself takes
               the arrow keys, so reordering stays reachable without a
               pointer. */
            tabIndex={0}
            onKeyDown={(e) => {
              if (e.key !== 'ArrowUp' && e.key !== 'ArrowDown') return
              e.preventDefault()
              move(i, e.key === 'ArrowUp' ? i - 1 : i + 1)
            }}
            {...drag.row(i)}
          >
            <span className="ladder-grip" aria-hidden="true">
              <Icon name="grip" size={11} />
            </span>
            <span className="ladder-name">{ASS_RUNGS[r].name}</span>
            <span className="dim ladder-note">{ASS_RUNGS[r].note}</span>
          </li>
        ))}
      </ol>
    </div>
  )
}

export default function Settings() {
  const [values, setValues] = useState<Record<string, string>>({})
  /// The bandwidth box's own copy, so a refusal can put the old value back.
  const [bandwidth, setBandwidth] = useState('')
  const [loaded, setLoaded] = useState(false)
  /// A failed load used to render the page anyway, with every control showing
  /// its default — which reads as "these are your settings" when the truth is
  /// "we have no idea what your settings are". Worse than a blank screen,
  /// because the next thing you do is change one.
  const [loadError, setLoadError] = useState('')
  const [attempt, setAttempt] = useState(0)
  const [saved, setSaved] = useState(false)
  const savedTimer = useRef<ReturnType<typeof setTimeout>>(undefined)

  const flash = () => {
    setSaved(true)
    clearTimeout(savedTimer.current)
    savedTimer.current = setTimeout(() => setSaved(false), 1200)
  }

  useEffect(() => {
    // Fenced for the same reason as Libraries: the error and its button now
    // stay up for the whole request, so a second Try again is possible, and
    // an older load rejecting last would put the Failed screen back over
    // settings that had arrived.
    let live = true
    fetchPrefs()
      .then((r) => {
        if (!live) return
        const v: Record<string, string> = {}
        for (const p of r.prefs) {
          if (p.scope === '') v[p.key] = p.value
        }
        setValues(v)
        setBandwidth(v['bandwidth_kbps'] ?? '')
        setLoadError('')
        setLoaded(true)
      })
      .catch((e) => {
        if (!live) return
        setLoadError(String(e))
        setLoaded(true)
      })
    return () => {
      live = false
    }
  }, [attempt])

  if (!loaded) return null
  if (loadError)
    return (
      <Failed
        what="Could not load your settings."
        message={loadError}
        // Neither the error nor `loaded` is dropped here: `if (!loaded) return
        // null` sits one line above, so clearing them blanked the page for the
        // whole request and then brought the same error back. They go when the
        // load answers.
        onRetry={() => setAttempt((n) => n + 1)}
      />
    )
  return (
    <main>
      <div className="settings-head">
        <h1>Settings</h1>
        {/* Always in the layout, only sometimes visible: a chip that
            appears would shift the heading every time you changed
            something. */}
        <span className={`chip saved-flash${saved ? ' on' : ''}`}>saved</span>
      </div>
      <p className="dim settings-intro">Everything here saves the moment you change it.</p>
      <div className="settings-cards">
        <section className="card-plain">
          <div className="card-head">
            <span className="card-glyph">
              <Icon name="download" size={15} />
            </span>
            <span className="card-name">OpenSubtitles</span>
            <span
              className={`chip mono ${values['opensubtitles.username'] ? '' : 'dim'} card-badge`}
            >
              {values['opensubtitles.username'] ? 'your budget' : 'shared budget'}
            </span>
          </div>
          <p className="dim card-prose">
            Subtitle search works without an account, on a small download budget shared by everyone
            on this server. Attach your own opensubtitles.com account to spend your own budget
            instead. Subtitles you download are shared with everyone here.
          </p>
          <OpenSubtitlesAccount
            username={values['opensubtitles.username'] ?? ''}
            hasPassword={!!values['opensubtitles.password']}
            onSaved={(u, p) =>
              setValues((cur) => ({
                ...cur,
                'opensubtitles.username': u,
                'opensubtitles.password': p,
              }))
            }
            flash={flash}
          />
        </section>
        <section className="card-plain">
          <div className="card-head">
            <span className="card-glyph">
              <Icon name="play" size={15} />
            </span>
            <span className="card-name">Playback</span>
          </div>
          <p className="dim card-prose">Applies wherever you play, on this account.</p>
          <div className="pref-row">
            <span className="pref-label mono">bandwidth</span>
            {/* Controlled, so a refusal can put it back. Uncontrolled, this was
                the one write on a page headed "everything here saves the moment
                you change it" that could keep showing a cap the server does not
                have — and the viewer's playback stays uncapped underneath it.
                Stored as the server stores it: `0` means no cap, and the pref
                is cleared rather than set to "0", so the local copy must be
                empty too or it disagrees with the hub about the same key. */}
            <input
              className="pref-input mono"
              type="number"
              min={0}
              placeholder="kbit/s cap (0 = none)"
              value={bandwidth}
              onChange={(e) => setBandwidth(e.currentTarget.value)}
              onBlur={(e) => {
                const raw = e.currentTarget.value.trim()
                const v = raw === '0' ? '' : raw
                if (v === (values['bandwidth_kbps'] ?? '')) return
                putPref('', 'bandwidth_kbps', v)
                  .then(() => {
                    setValues((cur) => ({ ...cur, bandwidth_kbps: v }))
                    setBandwidth(v)
                    flash()
                  })
                  .catch(() => {
                    setBandwidth(values['bandwidth_kbps'] ?? '')
                    notify('Could not save that — the server did not take it.')
                  })
              }}
            />
          </div>
          <p className="dim pref-note">
            A ceiling for how much data playback may use — worth setting on a metered or slow
            connection. Anything above it is re-encoded smaller; a file that cannot be re-encoded
            will refuse to play rather than stall. Leave it empty for no limit.
          </p>
          {/* HUB-32a/d: how styled (ASS) subtitles reach a client that
            cannot render them itself, as an ORDERED ladder. The server
            tries each rung in turn and takes the first one this client
            and this fleet can actually serve. `native` is not listed:
            it is not a fallback, and it always wins when the client
            declares it. */}
          <AssLadder
            value={values['ass_order'] ?? ''}
            onChange={(v) => setValues((cur) => ({ ...cur, ass_order: v }))}
            flash={flash}
          />
        </section>
        <div className="settings-group">
          <h2>Which tracks to start with</h2>
          <p className="dim card-prose">
            When you open something, the first language in each list that the file actually has is
            the one that plays. Drag a language to move it, or click it to make it your first
            choice. <span className="mono teal">original</span> means whatever language the title
            was made in. Picking a different track while watching only affects that title, and it
            wins over these.
          </p>
        </div>
        {MEDIA_TYPES.map((mt) => (
          <section className="card-plain" key={mt}>
            <div className="card-head">
              <span className="card-glyph">
                <Icon name={mt === 'movies' ? 'movie' : 'show'} size={15} />
              </span>
              <span className="card-name">{mt}</span>
            </div>
            {/* Anime's presentation first: it decides how the episode lists
              on the other screens are numbered, which is a bigger
              difference than a track order. */}
            {mt === 'anime' && (
              <div className="pref-row">
                <span className="pref-label mono">view</span>
                <span className="chips">
                  {(['seasons', 'native'] as const).map((v) => (
                    <button
                      key={v}
                      className={`chip toggle${(values['anime_view'] ?? 'seasons') === v ? ' on' : ''}`}
                      title={
                        v === 'seasons'
                          ? 'TVDB-style seasons (projected)'
                          : 'flat absolute numbering (AniDB-native)'
                      }
                      onClick={() =>
                        putPref('', 'anime_view', v)
                          .then(() => {
                            setValues((cur) => ({ ...cur, anime_view: v }))
                            flash()
                          })
                          .catch(() => notify('Could not save that — the server did not take it.'))
                      }
                    >
                      {v}
                    </button>
                  ))}
                </span>
              </div>
            )}
            {mt === 'anime' && (
              <p className="dim pref-note">
                {(values['anime_view'] ?? 'seasons') === 'seasons'
                  ? 'Numbered in seasons, the way most people know these shows.'
                  : 'Numbered straight through, the way they were broadcast.'}
              </p>
            )}
            {(['audio', 'subs'] as const).map((kind) => (
              <LangChips
                key={kind}
                mediaType={mt}
                kind={kind}
                value={values[`${kind}.${mt}`] ?? ''}
                onChange={(v) => setValues((cur) => ({ ...cur, [`${kind}.${mt}`]: v }))}
                flash={flash}
              />
            ))}
          </section>
        ))}
      </div>
    </main>
  )
}
