// web/src/views/Library.tsx
import { useEffect, useLayoutEffect, useRef, useState, type ReactNode } from 'react'
import { artworkUrl, fetchItems, fetchLibraries, isAdmin, type Item } from '../api'
import placeholder from '../assets/placeholder.svg'
import MatchDialog from './MatchDialog'

/// Items per request. Smaller than the hub's 200 default because a chunk
/// is now fetched to fill a viewport, not to be a page someone reads.
const CHUNK = 100
/// Rows kept live above and below the viewport, so a flick of the wheel
/// lands on cards that are already there.
const OVERSCAN = 3
/// Must match `.grid { gap }` in styles.css — the one number this file
/// cannot measure, because it is between the cells rather than in one.
const GAP = 12

// Kind glyph for the card art corner (feather icons, MIT).
function KindIcon({ kind }: { kind: string }) {
  const paths: Record<string, ReactNode> = {
    movie: (
      <>
        <rect x="2" y="2" width="20" height="20" rx="2.18" />
        <path d="M7 2v20M17 2v20M2 12h20M2 7h5M2 17h5M17 7h5M17 17h5" />
      </>
    ),
    show: (
      <>
        <rect x="2" y="7" width="20" height="15" rx="2" />
        <polyline points="17 2 12 7 7 2" />
      </>
    ),
    album: (
      <>
        <path d="M9 18V5l12-2v13" />
        <circle cx="6" cy="18" r="3" />
        <circle cx="18" cy="16" r="3" />
      </>
    ),
  }
  const glyph = paths[kind]
  if (!glyph) return null
  return (
    <span className="kind-badge" title={kind === 'show' ? 'series' : kind}>
      <svg
        width="14"
        height="14"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        {glyph}
      </svg>
    </span>
  )
}

function Card({
  item: i,
  onOpen,
  onMatch,
}: {
  item: Item
  onOpen: (id: string) => void
  onMatch: (item: Item) => void
}) {
  return (
    <>
      {isAdmin() && (i.kind === 'movie' || i.kind === 'show') && (
        <button
          className={`match-btn ${
            !i.match_confidence || i.match_confidence === 'miss' || i.match_confidence === 'rejected'
              ? 'miss'
              : i.match_confidence === 'weak'
                ? 'weak'
                : ''
          }`}
          title={
            i.match_confidence === 'weak'
              ? 'Uncertain match — review'
              : i.match_confidence === 'auto' || i.match_confidence === 'manual'
                ? 'Re-match metadata'
                : 'No metadata match — fix'
          }
          onClick={() => onMatch(i)}
        >
          <svg
            width="14"
            height="14"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <circle cx="11" cy="11" r="8" />
            <line x1="21" y1="21" x2="16.65" y2="16.65" />
          </svg>
        </button>
      )}
      <button
        className="card"
        onClick={() => onOpen(i.kind === 'track' && i.parent_id ? i.parent_id : i.id)}
      >
        <span className="card-artbox">
          <img
            className="card-art"
            src={artworkUrl(i.id, i.art_version, 'card')}
            loading="lazy"
            alt=""
            onError={(e) => {
              e.currentTarget.onerror = null
              e.currentTarget.src = placeholder
            }}
          />
          <KindIcon kind={i.kind} />
          {i.played && (
            <span className="seen-badge" title="seen">
              <svg
                width="14"
                height="14"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <polyline points="20 6 9 17 4 12" />
              </svg>
            </span>
          )}
          {!i.played && !!i.resume_position_ms && !!i.resume_duration_ms && (
            <span className="card-progress">
              <span
                className="card-progress-fill"
                style={{
                  width: `${Math.min(100, (i.resume_position_ms / i.resume_duration_ms) * 100)}%`,
                }}
              />
            </span>
          )}
        </span>
        <span className="card-title">{i.title}</span>
        <span className="card-meta mono">
          {i.kind === 'episode'
            ? `${i.parent_title ?? ''} · S${i.season ?? '?'}E${i.episode ?? '?'}`
            : i.kind === 'track'
              ? [i.artist, i.parent_title].filter(Boolean).join(' · ')
              : (i.kind === 'album' ? (i.artist ?? '—') : (i.year ?? '—'))}
          {i.kind === 'album' && i.year ? ` · ${i.year}` : ''}
          {i.sources > 1 ? ` · ${i.sources} sources` : ''}
        </span>
      </button>
    </>
  )
}

export default function Library({
  libraryId,
  query,
  onOpen,
  onResetSearch,
}: {
  libraryId: string
  /// Already debounced, and owned by the header's search box — on this
  /// screen that box filters this library.
  query: string
  onOpen: (id: string) => void
  /// The library title doubles as "show me everything again": the
  /// filter lives in the app header, so the view can only ask.
  onResetSearch: () => void
}) {
  const [name, setName] = useState('Library')
  const [sort, setSort] = useState('title')
  const [total, setTotal] = useState<number | null>(null)
  // Sparse: index in the FULL result set → item. Holes are rows that
  // exist and have not been fetched, which is not the same as rows that
  // do not exist, and the difference is what keeps the layout still.
  const [loaded, setLoaded] = useState<Map<number, Item>>(new Map())
  const [rows, setRows] = useState({ start: 0, end: 0 })
  // Measured, never assumed: the card art is `aspect-ratio: 1` on a fluid
  // grid column, so a row's height is a function of the window width.
  const [metric, setMetric] = useState<{ cols: number; rowH: number } | null>(null)
  // Width, not a resize counter: a resize that does not change the width
  // cannot change the column count or the row height.
  const [width, setWidth] = useState(() => window.innerWidth)
  const [error, setError] = useState('')
  const [matching, setMatching] = useState<Item | null>(null)

  const wrapRef = useRef<HTMLDivElement>(null)
  const gridRef = useRef<HTMLUListElement>(null)
  const asked = useRef(new Set<number>())
  // Bumped whenever the result set changes identity. A reply carrying an
  // older generation describes a library or a search we have left.
  const gen = useRef(0)

  // The generation whose first reply REPLACES what is on screen rather
  // than merging into it.
  const replacing = useRef(0)

  // Start over on a different result set — WITHOUT clearing what is
  // displayed. Blanking here emptied the page for the length of a round
  // trip, and an empty page is a different tree, so React unmounted the
  // search box mid-keystroke and took the caret with it. The old results
  // stay up until the new ones arrive to replace them.
  const reset = () => {
    gen.current += 1
    replacing.current = gen.current
    asked.current.clear()
    setRows({ start: 0, end: 0 })
  }

  const loadChunk = (chunk: number) => {
    if (asked.current.has(chunk)) return
    asked.current.add(chunk)
    const mine = gen.current
    fetchItems({ library: libraryId, q: query, sort, limit: CHUNK, offset: chunk * CHUNK })
      .then((r) => {
        if (mine !== gen.current) return
        const swap = replacing.current === mine
        if (swap) replacing.current = 0
        setTotal(r.total)
        setLoaded((prev) => {
          const next = swap ? new Map<number, Item>() : new Map(prev)
          r.items.forEach((it, k) => next.set(r.offset + k, it))
          return next
        })
      })
      .catch((e) => {
        if (mine !== gen.current) return
        asked.current.delete(chunk) // a failed chunk must be retryable
        setError(String(e))
      })
  }

  // Note: the query is NOT cleared here. Arriving from a search on the
  // home screen must land with that search still applied — it is the
  // whole point of following a library through from its results.
  useEffect(() => {
    reset()
    fetchLibraries()
      .then((r) => setName(r.libraries.find((l) => l.id === libraryId)?.name ?? 'Library'))
      .catch(() => {})
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [libraryId])

  // A new result set: forget everything and start from the top, because
  // scroll position in the old one means nothing in the new one.
  useEffect(() => {
    reset()
    window.scrollTo({ top: 0 })
    loadChunk(0)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [libraryId, query, sort])

  // Measure once there is a card to measure. Row pitch is the cell height
  // plus the gap; column count comes from the resolved track list, so it
  // agrees with what CSS actually did rather than with a copy of the rule.
  //
  // Deliberately NOT run on every render. Measuring writes state, so a
  // render-driven measurement is a cycle, and it only stays quiet while
  // every cell is the same height — one that is not locks the renderer.
  // These three inputs are the only things that can change the answer.
  useLayoutEffect(() => {
    const grid = gridRef.current
    const cell = grid?.firstElementChild as HTMLElement | null
    if (!grid || !cell) return
    const cols = getComputedStyle(grid).gridTemplateColumns.split(' ').filter(Boolean).length
    const rowH = cell.getBoundingClientRect().height + GAP
    if (!cols || rowH <= GAP) return
    if (!metric || metric.cols !== cols || Math.abs(metric.rowH - rowH) > 0.5) {
      setMetric({ cols, rowH })
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [total, width, loaded.size > 0])

  // Which rows the window is over. Re-run on scroll and on resize; resize
  // also invalidates the measurement, which the layout effect above
  // retakes on the next paint.
  useEffect(() => {
    const recompute = () => {
      const wrap = wrapRef.current
      if (!wrap || !metric || total === null) return
      const top = wrap.getBoundingClientRect().top + window.scrollY
      const firstVisible = Math.floor((window.scrollY - top) / metric.rowH)
      const deep = Math.ceil(window.innerHeight / metric.rowH)
      const totalRows = Math.ceil(total / metric.cols)
      const start = Math.max(0, firstVisible - OVERSCAN)
      const end = Math.min(totalRows - 1, firstVisible + deep + OVERSCAN)
      setRows((prev) => (prev.start === start && prev.end === end ? prev : { start, end }))
    }
    const onResize = () => {
      setWidth(window.innerWidth)
      recompute()
    }
    recompute()
    window.addEventListener('scroll', recompute, { passive: true })
    window.addEventListener('resize', onResize)
    return () => {
      window.removeEventListener('scroll', recompute)
      window.removeEventListener('resize', onResize)
    }
  }, [metric, total])

  // Fetch whatever the visible rows need and do not have.
  useEffect(() => {
    if (!metric || total === null) return
    const from = rows.start * metric.cols
    const to = Math.min(total - 1, rows.end * metric.cols + metric.cols - 1)
    for (let c = Math.floor(from / CHUNK); c <= Math.floor(to / CHUNK); c++) {
      if (!loaded.has(c * CHUNK)) loadChunk(c)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [rows, metric, total])

  // Deliberately no early `return` for loading or error. Every one of
  // them swaps the whole tree, and swapping the tree destroys the search
  // box the user is typing into. The chrome is always mounted; only what
  // hangs below it changes.
  const count = total ?? 0
  const cols = metric?.cols ?? 1
  const totalRows = Math.max(1, Math.ceil(count / cols))
  // Before the first measurement there is nothing to reserve against, so
  // render the first chunk plainly and let the layout effect measure it.
  const window_: number[] = []
  if (metric) {
    for (let r = rows.start; r <= rows.end; r++) {
      for (let c = 0; c < cols; c++) {
        const i = r * cols + c
        if (i < count) window_.push(i)
      }
    }
  } else {
    for (let i = 0; i < Math.min(CHUNK, count); i++) window_.push(i)
  }

  return (
    <main>
      <div className="library-head">
        <h1 className="clickable" onClick={onResetSearch}>
          {name}
        </h1>
        <select
          className="sort filter"
          value={sort}
          onChange={(e) => setSort(e.target.value)}
        >
          <option value="title">Title A–Z</option>
          <option value="-title">Title Z–A</option>
          <option value="-added">Recently added</option>
          <option value="added">Oldest added</option>
          <option value="-year">Newest first</option>
          <option value="year">Oldest first</option>
        </select>
        <span className="count mono">{total ?? ''}</span>
      </div>
      {error && <p className="error">{error}</p>}
      {total === 0 && (
        <p className="dim">
          {query
            ? `Nothing matches “${query}”.`
            : 'Nothing here yet. Attach a collection to this library and its scan will fill this page.'}
        </p>
      )}
      {/* The whole library's height is reserved from the first response,
          before a single card past the fold has been fetched. That is the
          difference from infinite scroll, where the page grows as you go
          and the scrollbar jumps under the thumb every time it does. */}
      <div
        className="grid-scroll"
        ref={wrapRef}
        style={metric ? { height: totalRows * metric.rowH - GAP } : undefined}
      >
        <ul
          className="grid"
          ref={gridRef}
          style={metric ? { transform: `translateY(${rows.start * metric.rowH}px)` } : undefined}
        >
          {window_.map((i) => {
            const item = loaded.get(i)
            return (
              <li key={i} className="card-cell">
                {item ? (
                  <Card item={item} onOpen={onOpen} onMatch={setMatching} />
                ) : (
                  // The SAME box, structurally — art, title line, meta
                  // line — not merely a similar one. A row that has not
                  // arrived must occupy exactly what it will occupy once
                  // it does, or the grid resizes as chunks land, which is
                  // the layout shift the reserved height exists to avoid.
                  // It also keeps row height a constant the measurement
                  // below can trust; when it did not, measuring a short
                  // placeholder and then a tall card re-entered the
                  // measure/render cycle and locked the renderer.
                  <div className="card card-pending" aria-hidden="true">
                    <span className="card-artbox">
                      <span className="card-art" />
                    </span>
                    <span className="card-title">&nbsp;</span>
                    <span className="card-meta mono">&nbsp;</span>
                  </div>
                )}
              </li>
            )
          })}
        </ul>
      </div>
      {matching && (
        <MatchDialog
          item={matching}
          onClose={() => setMatching(null)}
          onApplied={() => {
            // Re-fetch just the chunk the changed item lives in.
            const at = [...loaded.entries()].find(([, v]) => v.id === matching.id)?.[0]
            if (at !== undefined) {
              const chunk = Math.floor(at / CHUNK)
              asked.current.delete(chunk)
              loadChunk(chunk)
            }
          }}
        />
      )}
    </main>
  )
}

// web-next/src/views/Library.vue
<script setup lang="ts">
/// One library, as a grid whose whole height is reserved from the first
/// answer. Only the rows on screen exist in the DOM.
///
/// Deliberately no early return for loading or for an error. Every one of them
/// swaps the whole tree, and swapping the tree destroys the search box
/// somebody is typing into. The chrome is always mounted; only what hangs
/// below it changes.
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useQuery } from '@tanstack/vue-query'

import Btn from '../components/Btn.vue'
import Card from '../components/Card.vue'
import MatchDialog from '../components/MatchDialog.vue'
import {
  cellsIn,
  changed,
  CHUNK,
  chunksFor,
  countLine,
  GAP,
  type Metric,
  reservedHeight,
  shapeOf,
  visibleRows,
} from '../domain/virtual.ts'
import type { ItemRowI64 } from '../api/generated/model/itemRowI64.ts'
import { listLibraries } from '../api/generated/kahawai.ts'
import { notify } from '../composables/notices.ts'
import { sentence } from '../domain/refusal.ts'
import { targetOf } from '../domain/label.ts'
import { useLibraryItems } from '../composables/library.ts'
import { useSearchBox, useSearchQuery } from '../composables/search.ts'
import { whoAmI } from '../api/session.ts'

const route = useRoute()
const router = useRouter()

const library = computed(() => String(route.params.library ?? ''))
/// The header's box filters this library in place — see `useSearch`.
const query = useSearchQuery()
const sort = ref('title')

const { loaded, total, libraryTotal, failure, need, refresh, retry } = useLibraryItems(
  library,
  query,
  sort,
)

/// HUB-8 hand-matching, from the grid: an operator finds a wrong cover by
/// LOOKING at the covers, so the affordance belongs where they are looking.
/// Only for a work — an episode inherits its show's identity — and only for an
/// admin, who is the only one the endpoint answers.
const me = whoAmI()
const matchable = (item: ItemRowI64) => me.admin && (item.kind === 'movie' || item.kind === 'show')

const matching = ref<{ item: ItemRowI64; at: number } | null>(null)

/// Pressing the library's name drops the filter, which is the other half of
/// the ✕ in the box — the heading is where somebody looks when the page is
/// showing twelve of two thousand.
const search = useSearchBox()
function clearFilter() {
  search?.clear()
}

/// The library's name and media type. A second request, and a failure here is
/// a notice rather than the screen: this failing alone leaves a perfectly good
/// grid underneath it. Silence read as a library called "Library" holding
/// cards of the wrong shape — the media type is what decides whether a sleeve
/// is square.
const details = useQuery({
  queryKey: ['libraries'],
  queryFn: () => listLibraries(),
  select: (r) => r.libraries,
})
watch(
  () => details.isError.value,
  (failed) =>
    failed && notify(`Could not load the library details: ${sentence(details.error.value)}`),
)
const self = computed(() => details.data.value?.find((l) => l.id === library.value))
const name = computed(() => self.value?.name ?? 'Library')

/// Measured, never assumed: the card art's aspect ratio is applied to a fluid
/// grid column, so a row's height is a function of the window width.
const metric = ref<Metric | null>(null)
const rows = ref({ start: 0, end: 0 })
const wrap = ref<HTMLElement | null>(null)
const grid = ref<HTMLElement | null>(null)

function measure() {
  const el = grid.value
  const cell = el?.firstElementChild as HTMLElement | null
  if (!el || !cell) return
  const cols = getComputedStyle(el).gridTemplateColumns.split(' ').filter(Boolean).length
  const rowH = cell.getBoundingClientRect().height + GAP
  if (!cols || rowH <= GAP) return
  const now = { cols, rowH }
  if (changed(metric.value, now)) metric.value = now
}

function recompute() {
  if (!wrap.value || !metric.value || total.value === null) return
  const at = visibleRows(
    {
      wrapTop: wrap.value.getBoundingClientRect().top + window.scrollY,
      scrollY: window.scrollY,
      height: window.innerHeight,
    },
    metric.value,
    total.value,
  )
  if (at.start !== rows.value.start || at.end !== rows.value.end) rows.value = at
}

/// A ResizeObserver on the grid itself rather than a window resize listener.
///
/// The measurement is a function of the grid's WIDTH, and the window is not
/// the only thing that changes it: the vertical scrollbar cannot exist before
/// the first measurement — the wrapper has no height and the list is out of
/// flow, so the page does not scroll — and it appears the instant the reserved
/// height lands, narrowing every column after the only measurement that would
/// otherwise ever be taken.
let watching: ResizeObserver | undefined
function remeasure() {
  measure()
  recompute()
}
onMounted(() => {
  window.addEventListener('scroll', recompute, { passive: true })
  void nextTick(() => {
    // Once by hand, for the environment with no ResizeObserver in it. Where
    // there is one, `observe` fires it immediately and this is the same
    // measurement twice — which costs a `getComputedStyle` and is why the
    // guard below decides whether anything changed.
    remeasure()
    if (typeof ResizeObserver === 'undefined' || !grid.value) return
    watching = new ResizeObserver(remeasure)
    watching.observe(grid.value)
  })
})
onBeforeUnmount(() => {
  window.removeEventListener('scroll', recompute)
  watching?.disconnect()
})

/// Measure once there is a card to measure, and again when anything that can
/// change the answer changes. Deliberately not on every render: measuring
/// writes state, so a render-driven measurement is a cycle.
///
/// The media type is one of those inputs. It arrives a round trip after the
/// first cards, and without it a music library keeps the row pitch it measured
/// while its square sleeves were still poster-shaped — every row then
/// reserving a poster's height for a sleeve, so the reserved total ran long
/// and the last screenful was empty space.
watch([total, () => loaded.value.size > 0, () => self.value?.media_type], () =>
  nextTick(() => {
    measure()
    recompute()
  }),
)
watch([metric, total], recompute)

/// Fetch whatever the visible rows need and do not have.
watch(
  [rows, metric, total],
  () => {
    if (!metric.value || total.value === null) return
    need(chunksFor(rows.value, metric.value, total.value))
  },
  { immediate: true },
)

// A different result set: back to the top, because a scroll position in the
// old one means nothing in the new one — and then work out which rows that is.
//
// Without the recompute a re-sort left ten cards inside a full-height
// container for ever: scrolling to the top when already there fires no scroll
// event, and a re-sort changes neither the total nor the metric, so every
// other path that would have recomputed was watching something that had not
// moved.
watch([library, query, sort], () => {
  rows.value = { start: 0, end: 0 }
  window.scrollTo({ top: 0 })
  void nextTick(recompute)
})

/// Before the first measurement there is nothing to reserve against, so the
/// first chunk is rendered plainly and the measurement is taken off it.
const cells = computed(() => {
  const count = total.value ?? 0
  if (!metric.value) return Array.from({ length: Math.min(CHUNK, count) }, (_, n) => n)
  return cellsIn(rows.value, metric.value, count)
})

const height = computed(() =>
  metric.value && total.value !== null ? reservedHeight(total.value, metric.value) : undefined,
)
const offset = computed(() =>
  metric.value ? `translateY(${rows.value.start * metric.value.rowH}px)` : undefined,
)

function open(item: Parameters<typeof targetOf>[0]) {
  void router.push({
    name: 'detail',
    params: { library: library.value, id: targetOf(item) },
  })
}
</script>

<template>
  <main>
    <!-- The wordmark opens the jump menu now, so home needs saying
         somewhere. -->
    <Btn ghost small class="mb-4" @click="router.push({ name: 'libraries' })">← Home</Btn>
    <div class="mb-4 flex items-baseline gap-3">
      <!-- Pressable when there is a filter to drop, and inert when there is
           not: a heading that looks clickable and does nothing is worse than
           one that does not. -->
      <h1
        class="text-[22px] font-[650] tracking-[0.01em]"
        :class="query !== '' && 'cursor-pointer hover:text-teal'"
        @click="query !== '' && clearFilter()"
      >
        {{ name }}
      </h1>
      <select
        v-model="sort"
        class="ml-auto rounded-md border border-line bg-surface px-2 py-1 text-[13px]"
        aria-label="Sort"
      >
        <option value="title">Title A–Z</option>
        <option value="-title">Title Z–A</option>
        <option value="-added">Recently added</option>
        <option value="added">Oldest added</option>
        <option value="-year">Newest first</option>
        <option value="year">Oldest first</option>
      </select>
      <!-- The only feedback somebody who cannot see the grid gets that a
           filter or a sort did anything. -->
      <span class="font-mono text-dim" role="status">
        {{ countLine(total, libraryTotal, query !== '') }}
        <span class="sr-only">items</span>
      </span>
    </div>

    <!-- Always in the document, even empty: a live region inserted together
         with its text is commonly announced by nothing at all. `alert`, not
         `status`, because a chunk failing under a grid that looks full is not
         polite news — and the button is outside the region, or its label is
         read as part of the message every time the message changes. -->
    <div class="mb-3 flex items-center gap-3">
      <p class="m-0 text-warn" role="alert">{{ failure }}</p>
      <Btn v-if="failure" ghost small @click="retry">Try again</Btn>
    </div>

    <p v-if="total === 0" class="text-dim">
      {{
        query
          ? `Nothing matches “${query}”.`
          : 'Nothing here yet. Attach a collection to this library and its scan will fill this page.'
      }}
    </p>

    <!-- The whole library's height, reserved before a single card past the
         fold has been fetched. That is the difference from infinite scroll,
         where the page grows as you go and the scrollbar jumps under the thumb
         every time it does. -->
    <div ref="wrap" class="relative" :style="height !== undefined ? { height: `${height}px` } : {}">
      <!-- `role="list"`, because the reset that comes with Tailwind strips
           list semantics in Safari. `aria-setsize` because this list is
           virtualised: without it a 2242-item library announces as the ninety
           cells that happen to be mounted.
           The gap comes from the same constant the row pitch is measured
           against — it is the one number the component cannot measure, and it
           lived here as a literal while `GAP` lived in the module. -->
      <ul
        ref="grid"
        class="grid absolute top-0 right-0 left-0 will-change-transform"
        role="list"
        :style="{
          ...shapeOf(self?.media_type ?? ''),
          gap: `${GAP}px`,
          ...(offset ? { transform: offset } : {}),
        }"
      >
        <li v-for="at in cells" :key="at" :aria-setsize="total ?? -1" :aria-posinset="at + 1">
          <Card
            :item="loaded.get(at)"
            :matchable="!!loaded.get(at) && matchable(loaded.get(at)!)"
            @open="open"
            @match="matching = { item: loaded.get(at)!, at }"
          />
        </li>
      </ul>
    </div>

    <MatchDialog
      v-if="matching"
      :item="matching.item"
      @close="matching = null"
      @applied="refresh(matching!.at)"
    />
  </main>
</template>

<style scoped>
.grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(var(--card-min, 140px), 1fr));
}
</style>
