// web/src/components/Boundary.vue
<script setup lang="ts">
/// The last line: a screen that throws while rendering takes the app with it
/// and leaves a white page — no header, no way back, nothing to report but "it
/// went blank".
///
/// `onErrorCaptured` returning `false` stops the error propagating to the next
/// boundary up, which is what makes this a boundary rather than a spectator.
///
/// Note what this does NOT catch, so nobody trusts it too far: throws in event
/// handlers and in anything asynchronous never reach it. Those are the
/// `catch` blocks' job, and the screens that fetch handle them with `Failed`.
///
/// `resetKey` is which screen this is — see `boundaryKey`. Changing it clears
/// a latched error, so leaving a broken screen is enough; the same screen
/// re-rendering is not, or the failure would flicker back on every tick.
import { onErrorCaptured, ref, watch } from 'vue'

import Failed from './Failed.vue'

const props = defineProps<{ resetKey: string; away?: string | undefined }>()
const emit = defineEmits<{ away: [] }>()

const failure = ref<Error | null>(null)

onErrorCaptured((error) => {
  failure.value = error instanceof Error ? error : new Error(String(error))
  // The console is where a stack is actually readable, and this is a bug
  // rather than a condition — somebody should be able to find which component
  // died without reproducing it twice.
  console.error('render failed', error)
  return false
})

watch(
  () => props.resetKey,
  () => (failure.value = null),
)

/// Re-render the same screen from scratch. A render throw is usually a shape
/// the screen did not expect; asking again is worth one press before reaching
/// for a reload.
///
/// Clearing the failure is the whole of it. An earlier draft also bumped a
/// counter and put it on the slot as a `:key`, to "rebuild the subtree" — no
/// test could tell the difference with it removed, and a key on a slot outlet
/// is not a mechanism I could show working. A claim in a comment that nothing
/// can demonstrate is worse than no comment.
function retry() {
  failure.value = null
}
</script>

<template>
  <Failed
    v-if="failure"
    what="This screen stopped working."
    :message="failure.message || String(failure)"
    :away="props.away"
    @retry="retry"
    @away="emit('away')"
  />
  <!-- Leaving is not cleared here: the caller navigates, `resetKey` changes,
       and the watcher above does it. One mechanism, and it is the tested one.
       A navigation that does not happen — a guard refusing it — correctly
       leaves the failure on screen. -->
  <slot v-else />
</template>

// web/src/Boundary.tsx
import { Component, type ReactNode } from 'react'
import Failed from './Failed'

/// The last line: a screen that throws while rendering takes the whole app
/// with it, and React unmounts the tree rather than leaving a half-drawn
/// one. Without this that is a white page — no header, no way back, nothing
/// to report but "it went blank".
///
/// A class, because there is no hook form of this. `getDerivedStateFromError`
/// and `componentDidCatch` are the only way React offers to catch a render
/// throw, and both are class-only. It is the one class in the app and it is
/// not a style choice.
///
/// Note what this does NOT catch, so nobody trusts it too far: errors thrown
/// in event handlers, in promises, or in anything asynchronous. Those never
/// reach a boundary — they are the `catch` blocks' job, and the screens that
/// fetch handle them with `Failed` instead.
export default class Boundary extends Component<
  {
    children: ReactNode
    onHome: () => void
    /// Wraps the FAILURE only, never the children — so a boundary around a
    /// fixed-position thing can put its card where that thing was. The music
    /// dock is `position: fixed`, so its card landed at the end of the page
    /// flow: from the viewer's side the bar simply vanished, with the offer to
    /// retry several screens further down.
    className?: string
  },
  { error: Error | null }
> {
  state: { error: Error | null } = { error: null }

  static getDerivedStateFromError(error: Error) {
    return { error }
  }

  componentDidCatch(error: Error, info: { componentStack?: string | null }) {
    // The console is where a stack is actually readable, and this is a bug
    // rather than a condition — somebody should be able to find out which
    // component died without reproducing it twice.
    console.error('render failed', error, info.componentStack)
  }

  render() {
    const { error } = this.state
    if (!error) return this.props.children
    const card = (
      <Failed
        what="This screen stopped working."
        message={error.message || String(error)}
        // Re-render the same route from scratch. A render throw is usually a
        // shape the screen did not expect; asking again is worth one press
        // before reaching for a reload.
        onRetry={() => this.setState({ error: null })}
        away={{
          label: 'Home',
          go: () => {
            this.setState({ error: null })
            this.props.onHome()
          },
        }}
      />
    )
    const { className } = this.props
    return className ? <div className={className}>{card}</div> : card
  }
}
